import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CalendarDays, Users, Inbox, CircleDollarSign, Image, Settings, CreditCard, MapPin, ArrowRight, Plus } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { AppointmentActions } from "@/components/appointment-actions";
import { ManualAppointment } from "@/components/manual-appointment";

const links=[["Início","/app"],["Agenda","/app/agenda"],["Solicitações","/app/solicitacoes"],["Clientes","/app/clientes"],["Serviços","/app/servicos"],["Financeiro","/app/financeiro"],["Portfólio","/app/portfolio"],["Minha página","/app/minha-pagina"],["Configurações","/app/configuracoes"],["Assinatura","/app/assinatura"]];
const titles:Record<string,string>={agenda:"Agenda",solicitacoes:"Solicitações",clientes:"Clientes",financeiro:"Financeiro",portfolio:"Portfólio","minha-pagina":"Minha página",configuracoes:"Configurações",assinatura:"Assinatura"};
const explanations:Record<string,string>={agenda:"Seus próximos atendimentos e bloqueios aparecem aqui.",solicitacoes:"Revise pedidos, confirme ou converse sobre outro horário.",clientes:"O histórico das clientes atendidas no seu espaço.",financeiro:"Acompanhe valores previstos e recebidos.",portfolio:"Compartilhe fotos do seu trabalho na sua página.","minha-pagina":"Veja e compartilhe a página do seu negócio.",configuracoes:"Cuide das informações e da disponibilidade do seu espaço.",assinatura:"Acompanhe o período gratuito e sua assinatura."};
type Row={id:string;name?:string;phone?:string;status?:string;start_at?:string;service_name_snapshot?:string;amount_cents?:number;kind?:string;note?:string;created_at?:string;clients?:{name:string}|{name:string}[]|null};
function clientName(row:Row){return Array.isArray(row.clients)?row.clients[0]?.name:row.clients?.name}

export default async function WorkspaceSection({params}:{params:Promise<{section:string}>}){
 const {section}=await params;if(!titles[section])notFound();const supabase=await createClient();if(!supabase)redirect("/entrar");const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/entrar");
 const {data:member}=await supabase.from("business_members").select("business_id").eq("user_id",user.id).limit(1).maybeSingle();if(!member)redirect("/app/onboarding");
 const icon:Record<string,typeof CalendarDays>={agenda:CalendarDays,solicitacoes:Inbox,clientes:Users,financeiro:CircleDollarSign,portfolio:Image,"minha-pagina":MapPin,configuracoes:Settings,assinatura:CreditCard};const Icon=icon[section];let rows:Row[]=[];let services:{id:string;name:string;base_price_cents:number|null;base_duration_minutes:number|null}[]=[];
 if(section==="agenda"||section==="solicitacoes"){
  let query=supabase.from("appointments").select("id,status,start_at,service_name_snapshot,clients(name)").eq("business_id",member.business_id).order("start_at");
  if(section==="solicitacoes")query=query.in("status",["requested","under_review","proposed"]);else query=query.gte("start_at",new Date().toISOString());
  const {data}=await query.limit(80);rows=(data??[]) as unknown as Row[];
  if(section==="agenda"){const {data:availableServices}=await supabase.from("services").select("id,name,base_price_cents,base_duration_minutes").eq("business_id",member.business_id).eq("active",true).order("name");services=availableServices??[]}
 }else if(section==="clientes"){
  const {data}=await supabase.from("clients").select("id,name,phone,created_at").eq("business_id",member.business_id).order("name").limit(100);rows=(data??[]) as Row[];
 }else if(section==="financeiro"){
  const {data}=await supabase.from("financial_entries").select("id,kind,status,amount_cents,note,occurred_at").eq("business_id",member.business_id).order("occurred_at",{ascending:false}).limit(100);rows=(data??[]) as Row[];
 }
 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/app"><span className="brand-mark">t</span><span>tá marcado</span></Link><div className="side-label" style={{marginTop:25}}>Seu espaço</div>{links.map(([name,url])=><Link className={`side-link ${(section==="minha-pagina"?name==="Minha página":name.toLowerCase()===titles[section].toLowerCase())?"active":""}`} href={url} key={url}>{name}</Link>)}</aside><main className="app-main"><header className="app-top"><span style={{fontSize:13,color:"var(--muted)"}}>Seu espaço de atendimento</span><span className="avatar">{user.user_metadata.full_name?.slice(0,2)?.toUpperCase()??"TM"}</span></header><div className="app-content"><div className="dash-heading"><div><span className="eyebrow">Tá Marcado</span><h1>{titles[section]}</h1><p>{explanations[section]}</p></div>{section==="agenda"&&<ManualAppointment services={services}/ >}{section==="financeiro"&&<Link className="btn" href="/app/financeiro?novo=1"><Plus size={15}/> Registrar valor</Link>}</div>
 {rows.length>0?<section className="panel">{rows.map(row=><article className="appointment-row" key={row.id}><span className="avatar">{(clientName(row)??row.name??row.kind??"T").slice(0,1).toUpperCase()}</span><div className="row-main"><b>{clientName(row)??row.name??row.note??row.service_name_snapshot??"Registro"}</b><small>{row.phone??(row.start_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(row.start_at)):row.created_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium"}).format(new Date(row.created_at)):"")}{row.service_name_snapshot?` · ${row.service_name_snapshot}`:""}</small></div>{section==="solicitacoes"&&<AppointmentActions id={row.id} status={row.status??"requested"}/ >}{section==="agenda"&&<span className="status">{row.status??"Agendado"}</span>}{section==="financeiro"&&<span className="status">R$ {((row.amount_cents??0)/100).toFixed(2).replace(".",",")}</span>}</article>)}</section>:<section className="panel" style={{textAlign:"center",padding:"48px 24px"}}><Icon size={28} color="var(--green2)"/><h2 className="serif" style={{fontSize:28}}>{section==="agenda"?"Sua agenda começa aqui":section==="solicitacoes"?"Nenhuma solicitação por enquanto":section==="clientes"?"Sua lista começa com o primeiro atendimento":titles[section]}</h2><p style={{fontSize:13,color:"var(--muted)",maxWidth:430,margin:"0 auto 18px"}}>{explanations[section]}</p>{section==="minha-pagina"&&<Link className="btn" href="/app">Ver meu link <ArrowRight size={15}/></Link>}{section==="portfolio"&&<span className="pill">Envio de fotos em preparação</span>}{section==="assinatura"&&<span className="pill">10 primeiros atendimentos grátis · R$ 29,90/mês</span>}</section>}</div></main><nav className="mobile-nav">{links.slice(0,5).map(([name,url])=><Link className={name.toLowerCase()===titles[section]?.toLowerCase()?"active":""} href={url} key={url}>{name}</Link>)}</nav></div>;
}
