import { BrandLogo } from "@/components/brand-logo";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CalendarDays, Users, Inbox, CircleDollarSign, Image, Settings, CreditCard, MapPin, ArrowRight, Plus, ChevronLeft, ChevronRight } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { AppointmentActions } from "@/components/appointment-actions";
import { ManualAppointment } from "@/components/manual-appointment";
import { BusinessPixSettings } from "@/components/business-pix-settings";
import { BookingWindowSettings } from "@/components/booking-window-settings";
import { ProfessionalCalendar } from "@/components/professional-calendar";
import { BusinessProfileSettings } from "@/components/business-profile-settings";
import { QuestionManager } from "@/components/question-manager";
import { CancellationSeenAction } from "@/components/cancellation-seen-action";

const links=[["Início","/app"],["Agenda","/app/agenda"],["Solicitações","/app/solicitacoes"],["Clientes","/app/clientes"],["Lista de espera","/app/espera"],["Serviços","/app/servicos"],["Perguntas para clientes","/app/perguntas"],["Financeiro","/app/financeiro"],["Portfólio","/app/portfolio"],["Minha página","/app/minha-pagina"],["Configurações","/app/configuracoes"],["Assinatura","/app/assinatura"]];
const titles:Record<string,string>={agenda:"Agenda",solicitacoes:"Solicitações",clientes:"Clientes",espera:"Lista de espera",servicos:"Serviços",perguntas:"Perguntas para clientes",financeiro:"Financeiro",portfolio:"Portfólio","minha-pagina":"Minha página",configuracoes:"Configurações",assinatura:"Assinatura"};
const explanations:Record<string,string>={agenda:"Seus próximos atendimentos e bloqueios aparecem aqui.",solicitacoes:"Revise pedidos, confirme ou converse sobre outro horário.",clientes:"O histórico das clientes atendidas no seu espaço.",espera:"Contatos que autorizaram ser avisados se surgir uma possibilidade.",servicos:"Organize os serviços oferecidos no seu espaço.",perguntas:"Configure o que cada cliente precisa responder antes de solicitar um horário.",financeiro:"Acompanhe valores previstos e recebidos.",portfolio:"Compartilhe fotos do seu trabalho na sua página.","minha-pagina":"Veja e compartilhe a página do seu negócio.",configuracoes:"Cuide das informações e da disponibilidade do seu espaço.",assinatura:"Acompanhe o período gratuito e sua assinatura."};
type Row={id:string;name?:string;phone?:string;status?:string;payment_status?:string;signal_amount_cents?:number;start_at?:string;end_at?:string;closed_at?:string|null;service_name_snapshot?:string;client_name_snapshot?:string|null;price_estimate_cents?:number|null;client_cancellation_reason?:string|null;cancellation_seen_at?:string|null;amount_cents?:number;kind?:string;note?:string;created_at?:string;customer_name?:string;customer_phone?:string;preferred_date?:string|null;clients?:{name:string;phone:string}|{name:string;phone:string}[]|null;services?:{name:string}|{name:string}[]|null;appointment_answers?:{question_label:string;answer:unknown;price_delta_cents:number;duration_delta_minutes:number}[]};
function clientName(row:Row){return row.client_name_snapshot||(Array.isArray(row.clients)?row.clients[0]?.name:row.clients?.name)}
function requestPageNumbers(current:number,total:number){const pages=new Set([1,total,current-1,current,current+1]);return [...pages].filter(page=>page>=1&&page<=total).sort((a,b)=>a-b)}

export default async function WorkspaceSection({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{mes?:string;dia?:string;aba?:string;pagina?:string}>}){
 const [{section},{mes,dia,aba,pagina}]=await Promise.all([params,searchParams]);if(!titles[section])notFound();const supabase=await createClient();if(!supabase)redirect("/entrar");const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/entrar");
 const {data:member}=await supabase.from("business_members").select("business_id").eq("user_id",user.id).limit(1).maybeSingle();if(!member)redirect("/app/onboarding");
 const {data:business}=await supabase.from("businesses").select("name,timezone,signal_enabled").eq("id",member.business_id).maybeSingle();const timeZone=business?.timezone||"America/Sao_Paulo";const signalEnabled=business?.signal_enabled??true;
 const parts=new Intl.DateTimeFormat("en",{timeZone,year:"numeric",month:"2-digit"}).formatToParts(new Date());const currentMonth=`${parts.find(part=>part.type==="year")?.value}-${parts.find(part=>part.type==="month")?.value}`;
 const month=/^\d{4}-(0[1-9]|1[0-2])$/.test(mes??"")?mes!:currentMonth;const [year,monthNumber]=month.split("-").map(Number);const monthStart=new Date(Date.UTC(year,monthNumber-1,1)-24*60*60*1000);const monthEnd=new Date(Date.UTC(year,monthNumber,1)+24*60*60*1000);
 const todayParts=new Intl.DateTimeFormat("en",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const today=`${todayParts.find(part=>part.type==="year")?.value}-${todayParts.find(part=>part.type==="month")?.value}-${todayParts.find(part=>part.type==="day")?.value}`;
 const requestTabs=[{key:"andamento",label:"Solicitações em andamento"},{key:"aprovadas",label:"Solicitações aprovadas"},{key:"canceladas",label:"Solicitações canceladas"}];const requestTab=requestTabs.some(tab=>tab.key===aba)?aba!:"andamento";const requestPage=Math.max(1,Number.parseInt(pagina??"1",10)||1);let requestCount=0;let requestPages=0;
 const icon:Record<string,typeof CalendarDays>={agenda:CalendarDays,solicitacoes:Inbox,clientes:Users,espera:Users,servicos:CalendarDays,perguntas:Inbox,financeiro:CircleDollarSign,portfolio:Image,"minha-pagina":MapPin,configuracoes:Settings,assinatura:CreditCard};const Icon=icon[section];let rows:Row[]=[];let services:{id:string;name:string;base_price_cents:number|null;base_duration_minutes:number|null}[]=[];let agendaBlocks:{id:string;starts_at:string;ends_at:string;kind:string;label:string|null}[]=[];let questionServices:{id:string;name:string;questions:{id:string;label:string;field_type:string;required:boolean;options:{id:string;label:string;price_delta_cents:number;duration_delta_minutes:number}[]}[]}[]=[];let cancellationSeenAvailable=true;
 if(section==="agenda"||section==="solicitacoes"){
  const appointmentFields=section==="solicitacoes"?"id,status,payment_status,signal_amount_cents,start_at,end_at,created_at,closed_at,service_name_snapshot,client_name_snapshot,price_estimate_cents,client_cancellation_reason,clients(name,phone)":"id,status,payment_status,signal_amount_cents,start_at,end_at,created_at,closed_at,service_name_snapshot,client_name_snapshot,price_estimate_cents,clients(name,phone)";
  let query=supabase.from("appointments").select(appointmentFields,{count:section==="solicitacoes"?"exact":undefined}).eq("business_id",member.business_id).order(section==="solicitacoes"&&requestTab==="canceladas"?"closed_at":"start_at",{ascending:section==="agenda"||section==="solicitacoes"&&requestTab!=="canceladas"});
  if(section==="solicitacoes"){
   if(requestTab==="andamento")query=query.in("status",["requested","under_review","proposed","confirmed"]);
   else if(requestTab==="aprovadas")query=query.in("status",["completed","no_show"]);
   else query=query.in("status",["cancelled_by_client","cancelled_by_professional","expired"]);
   const from=(requestPage-1)*10;const {data,count}=await query.range(from,from+9);requestCount=count??0;requestPages=Math.ceil(requestCount/10);rows=(data??[]) as unknown as Row[];
  }else{const {data}=await query.gte("start_at",monthStart.toISOString()).lt("start_at",monthEnd.toISOString()).limit(80);rows=(data??[]) as unknown as Row[];}
  if(section==="solicitacoes"&&rows.length){const ids=rows.map(row=>row.id);const [{data:answers},{data:seenRows,error:seenError}]=await Promise.all([supabase.from("appointment_answers").select("appointment_id,question_label,answer,price_delta_cents,duration_delta_minutes").eq("business_id",member.business_id).in("appointment_id",ids),supabase.from("appointments").select("id,cancellation_seen_at").eq("business_id",member.business_id).in("id",ids)]);cancellationSeenAvailable=!seenError;const byAppointment=new Map<string,NonNullable<Row["appointment_answers"]>>();for(const answer of answers??[]){const list=byAppointment.get(answer.appointment_id)??[];list.push(answer);byAppointment.set(answer.appointment_id,list)}const seenByAppointment=new Map((seenRows??[]).map(item=>[item.id,item.cancellation_seen_at]));rows=rows.map(row=>({...row,appointment_answers:byAppointment.get(row.id)??[],cancellation_seen_at:seenByAppointment.get(row.id)??null}));}
  if(section==="agenda"){
   const [{data:availableServices},{data:exceptions}]=await Promise.all([
    supabase.from("services").select("id,name,base_price_cents,base_duration_minutes").eq("business_id",member.business_id).eq("active",true).order("name"),
    supabase.from("availability_exceptions").select("id,starts_at,ends_at,kind,label").eq("business_id",member.business_id).eq("kind","blocked").lt("starts_at",monthEnd.toISOString()).gt("ends_at",monthStart.toISOString()).order("starts_at")
   ]);services=availableServices??[];agendaBlocks=exceptions??[];
  }
 }else if(section==="clientes"){
  const {data}=await supabase.from("clients").select("id,name,phone,created_at,appointments(id,status,payment_status,signal_amount_cents,start_at,end_at,service_name_snapshot,client_name_snapshot,price_estimate_cents,agreed_price_cents,final_price_cents,customer_note,appointment_answers(question_label,answer,price_delta_cents,duration_delta_minutes))").eq("business_id",member.business_id).order("name").limit(100);rows=(data??[]) as Row[];
 }else if(section==="financeiro"){
  const {data}=await supabase.from("financial_entries").select("id,kind,status,amount_cents,note,occurred_at").eq("business_id",member.business_id).order("occurred_at",{ascending:false}).limit(100);rows=(data??[]) as Row[];
 }else if(section==="perguntas"){
  const [{data:serviceRows},{data:questionRows},{data:optionRows},{data:modifierRows}]=await Promise.all([
   supabase.from("services").select("id,name").eq("business_id",member.business_id).order("name"),
   supabase.from("service_questions").select("id,service_id,label,field_type,required,position").eq("business_id",member.business_id).eq("active",true).order("position"),
   supabase.from("service_question_options").select("id,question_id,label,position").eq("business_id",member.business_id).order("position"),
   supabase.from("service_modifiers").select("option_id,service_id,price_delta_cents,duration_delta_minutes").eq("business_id",member.business_id).eq("active",true)
  ]);
  questionServices=(serviceRows??[]).map(service=>({id:service.id,name:service.name,questions:(questionRows??[]).filter(question=>question.service_id===service.id).map(question=>({id:question.id,label:question.label,field_type:question.field_type,required:question.required,options:(optionRows??[]).filter(option=>option.question_id===question.id).map(option=>{const modifier=(modifierRows??[]).find(item=>item.option_id===option.id&&item.service_id===service.id);return{id:option.id,label:option.label,price_delta_cents:modifier?.price_delta_cents??0,duration_delta_minutes:modifier?.duration_delta_minutes??0}})}))}));
 }
 const emptyTitle=section==="solicitacoes"?"Nenhuma solicitação por enquanto":section==="clientes"?"Sua lista começa com o primeiro atendimento":titles[section];
 const appointmentList=<section className="panel">{rows.map(row=><article className="appointment-row" key={row.id}><div className="row-main"><b>{clientName(row)??row.name??row.note??row.service_name_snapshot??"Registro"}</b><small>{section==="solicitacoes"&&row.start_at?`Atendimento solicitado para ${new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(row.start_at))}`:row.phone??(row.start_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(row.start_at)):row.created_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium"}).format(new Date(row.created_at)):"")}{row.service_name_snapshot?` · ${row.service_name_snapshot}`:""}{row.payment_status==="signal_requested"?" · Aguardando sinal":""}{row.payment_status==="signal_reported"?" · Cliente avisou que pagou":""}</small>{section==="solicitacoes"&&row.created_at&&<small className="request-created-at">Solicitado em {new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(row.created_at))}</small>}</div>{section==="solicitacoes"&&row.status?.startsWith("cancelled")&&<span className="pill">{row.status==="cancelled_by_client"?"Cancelada pela cliente":"Cancelada pela profissional"}</span>}{section==="solicitacoes"&&row.status==="expired"&&<span className="pill">Expirada</span>}{section==="solicitacoes"&&row.status==="cancelled_by_client"&&row.client_cancellation_reason&&<small className="cancellation-reason"><b>Motivo:</b> {row.client_cancellation_reason}</small>}{section==="solicitacoes"&&requestTab==="canceladas"&&row.status==="cancelled_by_client"&&(row.cancellation_seen_at?<span className="pill">Já visualizada</span>:cancellationSeenAvailable?<CancellationSeenAction appointmentId={row.id}/ >:<small className="muted">Aplique a migration de cancelamentos vistos para habilitar esta ação.</small>)}{section==="solicitacoes"&&(requestTab==="andamento"||requestTab==="aprovadas")&&<AppointmentActions id={row.id} status={row.status??"requested"} paymentStatus={row.payment_status} signalEnabled={signalEnabled} clientPhone={Array.isArray(row.clients)?row.clients[0]?.phone:row.clients?.phone} clientName={clientName(row)} serviceName={row.service_name_snapshot} requestedAt={row.start_at} endAt={row.end_at} priceEstimateCents={row.price_estimate_cents} answers={row.appointment_answers}/ >}{section==="financeiro"&&<span className="status">R$ {((row.amount_cents??0)/100).toFixed(2).replace(".",",")}</span>}</article>)}</section>;
 const content=section==="agenda"?<ProfessionalCalendar month={month} today={today} selectedDay={dia} timeZone={timeZone} appointments={rows as (Row&{id:string;status:string;payment_status:string;start_at:string;end_at:string;service_name_snapshot:string;clients:NonNullable<Row["clients"]>})[]} blocks={agendaBlocks}/>:section==="configuracoes"?<div className="workspace-settings-stack"><BusinessProfileSettings/><BookingWindowSettings/><BusinessPixSettings/></div>:section==="perguntas"?<QuestionManager initialServices={questionServices}/>:section==="solicitacoes"?<><nav className="request-tabs" aria-label="Filtrar solicitações">{requestTabs.map(tab=><Link key={tab.key} href={`/app/solicitacoes?aba=${tab.key}&pagina=1`} className={`request-tab ${requestTab===tab.key?"active":""}`} aria-current={requestTab===tab.key?"page":undefined}>{tab.label}</Link>)}</nav>{rows.length?appointmentList:<section className="panel request-empty"><h2 className="serif">{requestTab==="andamento"?"Nenhuma solicitação em andamento":requestTab==="aprovadas"?"Nenhuma solicitação aprovada":"Nenhuma solicitação cancelada"}</h2><p>Quando houver solicitações nesta categoria, elas aparecerão aqui.</p></section>}{requestPages>1&&<nav className="request-pagination" aria-label="Páginas de solicitações"><Link aria-label="Página anterior" aria-disabled={requestPage<=1} className={`request-page-arrow ${requestPage<=1?"disabled":""}`} href={`/app/solicitacoes?aba=${requestTab}&pagina=${Math.max(1,requestPage-1)}`}><ChevronLeft size={17}/></Link>{requestPageNumbers(requestPage,requestPages).map((page,index,all)=><span className="request-page-group" key={page}>{index>0&&page-all[index-1]>1&&<span className="request-page-ellipsis">…</span>}<Link aria-current={page===requestPage?"page":undefined} className={`request-page ${page===requestPage?"active":""}`} href={`/app/solicitacoes?aba=${requestTab}&pagina=${page}`}>{page}</Link></span>)}<Link aria-label="Próxima página" aria-disabled={requestPage>=requestPages} className={`request-page-arrow ${requestPage>=requestPages?"disabled":""}`} href={`/app/solicitacoes?aba=${requestTab}&pagina=${Math.min(requestPages,requestPage+1)}`}><ChevronRight size={17}/></Link></nav>}</>:rows.length?appointmentList:section==="clientes"?<div className="panel"><p className="settings-intro">Clientes que já solicitaram ou realizaram um atendimento com você.</p></div>:<section className="panel" style={{textAlign:"center",padding:"48px 24px"}}><Icon size={28} color="var(--green2)"/><h2 className="serif" style={{fontSize:28}}>{emptyTitle}</h2><p style={{fontSize:13,color:"var(--muted)",maxWidth:430,margin:"0 auto 18px"}}>{explanations[section]}</p>{section==="minha-pagina"&&<Link className="btn" href="/app">Ver meu link <ArrowRight size={15}/></Link>}{section==="portfolio"&&<span className="pill">Envio de fotos em preparação</span>}{section==="assinatura"&&<span className="pill">10 primeiros atendimentos grátis · R$ 49,99/mês</span>}</section>;
 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/app"><BrandLogo /></Link><div className="side-label" style={{marginTop:25}}>Seu espaço</div>{links.map(([name,url])=><Link className={`side-link ${(section==="minha-pagina"?name==="Minha página":name.toLowerCase()===titles[section].toLowerCase())?"active":""}`} href={url} key={url}>{name}</Link>)}</aside><main className="app-main"><header className="app-top"><span style={{fontSize:13,color:"var(--muted)"}}>Seu espaço de atendimento</span></header><div className="app-content"><div className="dash-heading"><div><span className="eyebrow">Tá Marcado</span><h1>{titles[section]}</h1><p>{explanations[section]}</p></div>{section==="agenda"&&<ManualAppointment services={services}/ >}{section==="financeiro"&&<Link className="btn" href="/app/financeiro?novo=1"><Plus size={15}/> Registrar valor</Link>}</div>{content}</div></main><nav className="mobile-nav" aria-label="Navegação do espaço">{links.map(([name,url])=><Link className={url===`/app/${section}`?"active":""} href={url} key={url}>{name}</Link>)}</nav></div>;
}
