/** Public origin used for redirects generated by server-side routes.
 * Falls back to the incoming request origin for local development only.
 */
export function getSiteUrl(requestUrl?: string): URL {
  const configured = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (configured) return new URL(configured);
  return new URL(requestUrl ?? "http://localhost:3000");
}

export function siteUrl(path: string, requestUrl?: string): URL {
  return new URL(path, getSiteUrl(requestUrl));
}
