import Link from "next/link";
import { redirect } from "next/navigation";
import { CalendarDays, ChevronRight, CircleDollarSign, Clock3, Plus, Users, Scissors, Inbox, Image, Settings, CreditCard, House, Check } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { CopyLink } from "@/components/copy-link";
import { trialMessage } from "@/lib/domain";

const menu = [[House,"Início","/app"],[CalendarDays,"Agenda","/app/agenda"],[Inbox,"Solicitações","/app/solicitacoes"],[Users,"Clientes","/app/clientes"],[Scissors,"Serviços","/app/servicos"],[CircleDollarSign,"Financeiro","/app/financeiro"],[Image,"Portfólio","/app/portfolio"],[Settings,"Configurações","/app/configuracoes"],[CreditCard,"Assinatura","/app/assinatura"]] as const;
type Appointment={id:string;start_at:string;status:string;service_name_snapshot:string;clients:{name:string}|{name:string}[]|null};

export default async function Dashboard() {
  const supabase=await createClient();if(!supabase)redirect("/entrar?erro=config");
  const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/entrar");
  const {data:membership}=await supabase.from("business_members").select("business_id").eq("user_id",user.id).limit(1).maybeSingle();
  if(!membership)redirect("/app/onboarding");
  const [{data:business},{data:profile},{data:trial},{data:records},{count:pendingCount}]=await Promise.all([
    supabase.from("businesses").select("id,name,slug,timezone,published_at").eq("id",membership.business_id).single(),
    supabase.from("professional_profiles").select("display_name").eq("business_id",membership.business_id).maybeSingle(),
    supabase.from("trial_usage").select("eligible_completed_count").eq("business_id",membership.business_id).maybeSingle(),
    supabase.from("appointments").select("id,start_at,status,service_name_snapshot,clients(name)").eq("business_id",membership.business_id).in("status",["confirmed","requested","under_review","proposed"]).gte("start_at",new Date().toISOString()).order("start_at").limit(30),
    supabase.from("appointments").select("id",{count:"exact",head:true}).eq("business_id",membership.business_id).in("status",["requested","under_review","proposed"])
  ]);
  if(!business)redirect("/app/onboarding");
  const rows=(records??[]) as unknown as Appointment[];const timeZone=business.timezone||"America/Sao_Paulo";
  const formatDate=(date:Date,opts:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat("pt-BR",{...opts,timeZone}).format(date);
  const today=formatDate(new Date(),{year:"numeric",month:"2-digit",day:"2-digit"});
  const todayRows=rows.filter(row=>formatDate(new Date(row.start_at),{year:"numeric",month:"2-digit",day:"2-digit"})===today);
  const used=trial?.eligible_completed_count??0;const firstName=(profile?.display_name??user.user_metadata.full_name??business.name).split(" ")[0];
  const baseUrl=process.env.NEXT_PUBLIC_SITE_URL??"https://tamarcado.com.br";const profileUrl=`${baseUrl}/${business.slug}`;
  return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><Link className="brand" href="/"><span className="brand-mark">t</span><span>tá marcado</span></Link></div><div className="side-label">Seu espaço</div>{menu.map(([Icon,label,href],i)=><Link className={`side-link ${i===0?"active":""}`} href={href} key={label}><Icon size={17}/>{label}</Link>)}<div className="side-bottom"><div className="side-label">Sua página</div><a className="side-link" href={profileUrl} target="_blank" rel="noreferrer"><span className="brand-mark" style={{width:26,height:26,fontSize:15}}>{firstName.slice(0,1)}</span>Ver página pública <ChevronRight size={14}/></a></div></aside>
    <main className="app-main"><header className="app-top"><span style={{fontSize:13,color:"var(--muted)"}}>{new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"long",timeZone}).format(new Date())}</span><div style={{display:"flex",alignItems:"center",gap:10}}><span className="pill">{used>=10?"Assinatura necessária":"Plano gratuito"}</span><span className="avatar">{firstName.slice(0,2).toUpperCase()}</span></div></header><div className="app-content"><div className="dash-heading"><div><h1>Bom dia, {firstName} ☀️</h1><p>Veja o que acontece no seu espaço hoje.</p></div><Link className="btn" href="/app/agenda"><Plus size={16}/> Novo atendimento</Link></div>{trialMessage(used)&&<section className="trial-box" style={{marginBottom:18,background:"#f4eee0"}}><p style={{margin:0,lineHeight:1.6,color:"var(--ink)"}}>{trialMessage(used)}</p>{used>=10&&<Link className="btn small" style={{marginTop:13}} href="/app/assinatura">Continuar com assinatura</Link>}</section>}<div className="stats"><article className="stat-card"><span className="stat-label">Atendimentos hoje</span><div className="stat-value">{todayRows.filter(row=>row.status==="confirmed").length}</div><span className="stat-note">{todayRows[0]?`Próximo às ${formatDate(new Date(todayRows[0].start_at),{hour:"2-digit",minute:"2-digit"})}`:"Sua agenda está livre"}</span></article><article className="stat-card"><span className="stat-label">Aguardando resposta</span><div className="stat-value">{pendingCount??0}</div><span className="stat-note">Solicitações para revisar</span></article><article className="stat-card"><span className="stat-label">Próximos atendimentos</span><div className="stat-value">{rows.filter(row=>row.status==="confirmed").length}</div><span className="stat-note">Na sua agenda</span></article><article className="stat-card"><span className="stat-label">Seu negócio</span><div className="stat-value" style={{fontSize:24}}>{business.name}</div><span className="stat-note">Página {business.published_at?"publicada":"ainda não publicada"}</span></article></div>
      <div className="dash-grid"><section className="panel"><div className="panel-title"><span>Próximos atendimentos</span><Link href="/app/agenda" style={{fontSize:12,color:"var(--green2)"}}>Ver agenda <ChevronRight size={14}/></Link></div>{rows.length?rows.slice(0,5).map(row=>{const client=Array.isArray(row.clients)?row.clients[0]:row.clients;return <div className="appointment-row" key={row.id}><span className="time-col">{formatDate(new Date(row.start_at),{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</span><span className="avatar">{(client?.name??"C").slice(0,1).toUpperCase()}</span><div className="row-main"><b>{client?.name??"Cliente"}</b><small>{row.service_name_snapshot}</small></div><span className="status">{row.status==="confirmed"?"Confirmado":"Aguardando"}</span></div>}):<div style={{padding:"25px 8px",textAlign:"center",color:"var(--muted)",fontSize:13}}>Sua agenda ainda está livre. Compartilhe sua página para receber solicitações.</div>}</section><div><section className="panel"><div className="panel-title"><span>Seu Tá Marcado</span><span style={{color:"var(--green2)"}}><Check size={16}/></span></div><p style={{fontSize:12,color:"var(--muted)",lineHeight:1.6,margin:"-7px 0 16px"}}>Compartilhe sua página com suas clientes.</p><div className="quick-action" style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><a href={profileUrl} target="_blank" rel="noreferrer" style={{fontSize:12,overflowWrap:"anywhere"}}>{profileUrl}</a><CopyLink value={profileUrl}/></div></section><section className="trial-box"><div className="trial-top"><span>Atendimentos grátis</span><span>{used} de 10</span></div><div className="progress"><span style={{width:`${Math.min(100,used*10)}%`}}/></div><p>Contam apenas os atendimentos públicos concluídos. Os manuais ficam de fora.</p><Link href="/app/assinatura" style={{display:"inline-block",fontSize:11,fontWeight:700,color:"var(--green)",marginTop:12}}>Entenda seu plano <ChevronRight size={13}/></Link></section><section className="panel" style={{marginTop:14}}><div className="panel-title">Atalhos</div><div className="quick-grid"><Link className="quick-action" href="/app/servicos"><Scissors size={16}/><b>Adicionar serviço</b></Link><Link className="quick-action" href="/app/agenda"><Clock3 size={16}/><b>Configurar horários</b></Link></div></section></div></div></div></main><nav className="mobile-nav">{menu.slice(0,5).map(([Icon,label,href],i)=><Link className={i===0?"active":""} href={href} key={label}><Icon size={19}/>{label}</Link>)}</nav></div>;
}
