import { BrandLogo } from "@/components/brand-logo";
import Link from "next/link";
import { ArrowDown, ArrowRight, CalendarDays, Check, Clock3, Instagram, Menu, Sparkles } from "lucide-react";

const categories = ["Tranças", "Unhas", "Cílios", "Sobrancelhas", "Depilação", "Maquiagem", "Cabelo", "Estética"];
const faqs = [
  ["Preciso de cartão para começar?", "Não. Você começa sem cadastrar cartão e pode experimentar seus primeiros 10 atendimentos públicos."],
  ["Quanto custa depois?", "Um único plano de R$ 29,90 por mês, sem comissão sobre os seus atendimentos."],
  ["Minha cliente precisa criar conta?", "Não. Ela solicita e acompanha o atendimento por um link seguro."],
  ["Posso cadastrar qualquer serviço?", "Sim. Você define perguntas, preço e duração para o seu jeito de atender."],
  ["O que acontece depois dos 10 atendimentos?", "Seus dados e sua agenda continuam acessíveis. Novos agendamentos pela página pausam até ativar a assinatura."],
  ["Posso cancelar quando quiser?", "Sim. A assinatura é mensal e pode ser cancelada quando você decidir."]
];

export default function Home() {
  return <>
    <header className="wrap topbar"><Link className="brand" href="/"><BrandLogo /></Link><nav className="navlinks"><a href="#como-funciona">Como funciona</a><a href="#preco">Preço</a><a href="#duvidas">Dúvidas</a><Link href="/demo">Ver demonstração</Link><Link href="/entrar">Entrar</Link><Link className="btn small" href="/cadastro">Criar meu Tá Marcado <ArrowRight size={15}/></Link></nav></header>
    <main>
      <section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">A agenda que trabalha com você</span><h1 className="serif">Seu trabalho merece mais que uma agenda no <em>WhatsApp.</em></h1><p className="hero-copy">Crie sua página, organize seus horários e deixe suas clientes marcarem com você. Tudo no seu ritmo, do seu jeito.</p><div className="hero-actions"><Link className="btn" href="/cadastro">Criar meu Tá Marcado <ArrowRight size={16}/></Link><a className="btn secondary" href="#como-funciona"><ArrowDown size={15}/> Ver como funciona</a></div><p className="hero-note">10 primeiros atendimentos grátis · Sem cartão · Depois R$ 29,90/mês</p><div className="trust-row"><span>Feito para o seu negócio</span><span>Sem comissão</span><span>Cliente sem cadastro</span></div></div>
        <div className="hero-art" aria-label="Prévia de uma página profissional no celular"><div className="art-blob"/><div className="float-card float-one"><span className="float-check"><Check size={13}/></span> link pronto para compartilhar<strong>tamarcado.com/ana-trancas</strong></div><div className="phone"><div className="phone-notch"/><div className="phone-cover"/><div className="phone-info"><span className="eyebrow">Tranças · Salvador</span><h3>Ana Souza</h3><p>Tranças feitas com cuidado, no seu tempo.</p><div className="mini-service"><span><b>Box braids</b><br/>a partir de R$ 220 · 4h</span><span>›</span></div><div className="mini-service"><span><b>Twist nagô</b><br/>a partir de R$ 160 · 3h</span><span>›</span></div><div className="mini-cta">Escolher um horário</div></div></div><div className="float-card float-two"><span className="eyebrow">Sua semana</span><strong>Agenda em ordem</strong><Clock3 size={13}/> 3 horários confirmados</div></div>
      </div></section>
      <section className="pain"><div className="wrap pain-grid"><div><span className="eyebrow">Seu talento merece espaço</span><h2 className="section-title serif">Do direct para um lugar só seu.</h2><p className="section-copy">Chega de procurar conversa antiga para lembrar o horário, o preço ou aquela foto de referência.</p></div><div className="message-stack"><div className="message"><small>Instagram · ontem, 22:14</small>Oi, tem horário sábado? E quanto fica?</div><div className="message"><small>WhatsApp · hoje, 08:03</small>Você consegue me mandar de novo aquela foto?</div><div className="message"><small>Você · hoje, 09:21</small>Tenho sim! Só um minutinho que vou olhar a agenda…</div><div className="message"><small>Tá Marcado</small>Serviços, horários e pedidos organizados numa página só. <Check size={13}/></div></div></div></section>
      <section id="como-funciona" className="section"><div className="wrap"><span className="eyebrow">Leve do começo ao fim</span><h2 className="section-title serif">Seu jeito de atender,<br/>agora mais organizado.</h2><p className="section-copy">Em poucos minutos, você configura sua página e pode compartilhar seu link por onde suas clientes já falam com você.</p><div className="steps">{[["01","Crie sua página","Seu nome, seu trabalho e um link fácil de encontrar."],["02","Cadastre seus serviços","Explique o que oferece, quanto custa e quanto tempo leva."],["03","Compartilhe seu link","Coloque na bio, mande no WhatsApp ou imprima seu QR Code."],["04","Receba solicitações","Sua cliente escolhe o serviço e envia o melhor horário."],["05","Revise com calma","Confirme ou combine outro horário pelo Tá Marcado."],["06","Pode respirar","Sua agenda e seus atendimentos ficam organizados." ]].map(([n,t,d])=><article className="step-card" key={n}><span className="step-num">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
      <section className="section" style={{paddingTop:0}}><div className="wrap"><div className="feature-grid"><article className="feature-card"><span className="eyebrow">Uma página com a sua cara</span><h3 className="serif">Seu trabalho merece ser visto.</h3><p>Apresente seu portfólio, explique seus serviços e conte um pouco sobre você. Um cantinho profissional para compartilhar em qualquer lugar.</p><div className="pill">tamarcado.com.br/ana-trancas <ArrowRight size={13}/></div></article><article className="feature-card dark"><span className="eyebrow">Para muitos jeitos de cuidar</span><h3 className="serif">Seu talento, suas regras.</h3><p>De tranças a maquiagem, cada serviço pode ter as perguntas e os detalhes que fazem sentido para você.</p><div className="service-chips">{categories.map(c=><span key={c}>{c}</span>)}</div></article><article className="feature-card dark"><span className="eyebrow">Agenda inteligente</span><h3 className="serif">Horário que cabe no seu dia.</h3><p>A duração de cada serviço ajuda a mostrar horários possíveis de verdade. Sem encaixe impossível no fim do expediente.</p><div className="calendar-art"><div className="cal-line"><span>Hoje, quinta-feira</span><b>3 atendimentos</b></div><div className="cal-line"><span>09:00 · Box braids</span><b>Confirmado</b></div><div className="cal-line"><span>14:30 · Manutenção</span><b>Confirmado</b></div></div></article><article className="feature-card"><span className="eyebrow">Tudo no lugar</span><h3 className="serif">Menos procura. Mais presença.</h3><p>Solicitações, clientes, serviços, valores e histórico perto de você — no celular ou computador.</p><div className="service-chips"><span><CalendarDays size={13}/> Agenda</span><span>Clientes</span><span>Solicitações</span><span>Histórico</span></div></article></div></div></section>
      <section id="preco" className="section" style={{paddingTop:0}}><div className="wrap"><span className="eyebrow">Simples assim</span><h2 className="section-title serif">Um plano. Sem surpresas.</h2><div className="price-card"><div><span className="pill"><Sparkles size={13}/> 10 primeiros atendimentos grátis</span><div className="price-big" style={{marginTop:14}}>R$ 29,90 <small>/ mês</small></div><p>Sem comissão. Sem cartão para começar. Cancele quando quiser.</p></div><Link className="btn" href="/cadastro">Começar grátis <ArrowRight size={16}/></Link></div></div></section>
      <section className="section map-section"><div className="wrap"><span className="pill">Em breve</span><h2 className="section-title serif">Seu próximo horário pode estar mais perto do que você imagina.</h2><p className="section-copy">Encontre profissionais, conheça seus trabalhos e descubra quem tem o horário perfeito para você.</p><div className="map-box" aria-label="Prévia ilustrativa do mapa futuro">{[ ["18%","29%"],["45%","54%"],["68%","30%"],["84%","68%"],["30%","76%"],["57%","82%"] ].map(([left,top],i)=><span className="pin" key={i} style={{left,top}}/>)}</div></div></section>
      <section id="duvidas" className="section"><div className="wrap"><span className="eyebrow">Pode perguntar</span><h2 className="section-title serif">Dúvidas que podem aparecer.</h2><div className="faq-list">{faqs.map(([q,a])=><details className="faq-item" key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
      <section className="final-cta"><span className="eyebrow">Seu próximo passo</span><h2 className="serif">Sua próxima cliente pode estar esperando um horário.</h2><Link className="btn" href="/cadastro">Criar meu Tá Marcado <ArrowRight size={16}/></Link></section>
    </main><footer className="wrap footer"><Link className="brand" href="/"><BrandLogo /></Link><span>Seu trabalho. Seus horários. Seu Tá Marcado.</span><span><Link href="/termos">Termos</Link> · <Link href="/privacidade">Privacidade</Link></span></footer>
  </>;
}
