"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, X, Clock3, CalendarClock } from "lucide-react";

export function AppointmentActions({id,status}:{id:string;status:string}){
 const router=useRouter();const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [proposing,setProposing]=useState(false);
 async function update(next:string,changes:Record<string,unknown>={}){setBusy(true);setError("");try{const response=await fetch(`/api/appointments/${id}/transition`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status:next,changes})});const result=await response.json();if(!response.ok)throw new Error(result.error);setProposing(false);router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível atualizar.")}finally{setBusy(false)}}
 async function propose(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);const duration=Number(values.get("duration"));const price=String(values.get("price")??"");await update("proposed",{requested_date:values.get("date"),requested_time:values.get("time"),...(duration?{duration_minutes:duration}:{}),...(price?{price_cents:Math.round(Number(price)*100)}:{})})}
 return <div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end",alignItems:"center"}}>{["requested","under_review","proposed"].includes(status)&&<><button aria-label="Confirmar" title="Confirmar horário solicitado" className="pill" disabled={busy} onClick={()=>update("confirmed")}><Check size={14}/> Confirmar</button><button aria-label="Recusar" title="Recusar" className="pill" disabled={busy} onClick={()=>update("cancelled_by_professional")}><X size={14}/> Recusar</button><button className="pill" disabled={busy} onClick={()=>setProposing(!proposing)}><CalendarClock size={14}/> Sugerir horário</button>{status==="requested"&&<button className="pill" disabled={busy} onClick={()=>update("under_review")}><Clock3 size={14}/> Analisar</button>}</>}{status==="confirmed"&&<button className="pill" disabled={busy} onClick={()=>update("completed")}>Concluir</button>}{proposing&&<form onSubmit={propose} className="panel" style={{width:"100%",display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><div className="form-field"><label>Outro dia</label><input name="date" type="date" min={new Date().toLocaleDateString("en-CA")} required/></div><div className="form-field"><label>Horário</label><input name="time" type="time" required/></div><div className="form-field"><label>Duração (min)</label><input name="duration" type="number" min="1" max="1440"/></div><div className="form-field"><label>Valor (R$)</label><input name="price" type="number" min="0" step="0.01"/></div><button className="btn" style={{gridColumn:"1 / -1"}} disabled={busy}>Enviar proposta</button></form>}{error&&<span className="form-error">{error}</span>}</div>;
}
