"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, X, Clock3, CalendarClock } from "lucide-react";

export function AppointmentActions({id,status,paymentStatus,clientPhone,serviceName,requestedAt}:{id:string;status:string;paymentStatus?:string;clientPhone?:string;serviceName?:string;requestedAt?:string}){
 const router=useRouter();const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [proposing,setProposing]=useState(false);
 async function update(next:string,changes:Record<string,unknown>={}){setBusy(true);setError("");try{const response=await fetch(`/api/appointments/${id}/transition`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status:next,changes})});const result=await response.json();if(!response.ok)throw new Error(result.error);setProposing(false);router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível atualizar.")}finally{setBusy(false)}}
 async function signal(action:"request"|"verify"){setBusy(true);setError("");const popup=clientPhone?window.open("about:blank","_blank"):null;try{const response=await fetch(`/api/appointments/${id}/signal`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const result=await response.json();if(!response.ok)throw new Error(result.error);const trackingUrl=`${window.location.origin}/r/${result.tracking_token}`;if(popup&&action==="request"){const deadline=new Intl.DateTimeFormat("pt-BR",{timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(result.signal_deadline));const text=`Olá! Confirmei seu horário para ${serviceName??"seu atendimento"}. Para reservar, pague o sinal de R$ ${(Number(result.signal_amount_cents)/100).toFixed(2).replace(".",",")} via Pix (${result.pix_holder}): ${result.pix_key}. A vaga fica reservada por 1 hora, até ${deadline}. Acompanhe e avise sobre o pagamento neste link: ${trackingUrl}`;const digits=clientPhone!.replace(/\D/g,"");const phone=digits.length===10||digits.length===11?`55${digits}`:digits;popup.location.href=`https://wa.me/${phone}?text=${encodeURIComponent(text)}`}else if(popup&&action==="verify"){const text=`Olá! Conferi seu Pix e confirmei seu atendimento de ${serviceName??"serviço"} para ${requestedAt?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(requestedAt)):"a data combinada"}. Obrigada pela confiança. Tá Marcado! Acompanhe seu pedido por aqui: ${trackingUrl}`;const digits=clientPhone!.replace(/\D/g,"");const phone=digits.length===10||digits.length===11?`55${digits}`:digits;popup.location.href=`https://wa.me/${phone}?text=${encodeURIComponent(text)}`}else popup?.close();router.refresh()}catch(reason){popup?.close();setError(reason instanceof Error?reason.message:"Não foi possível atualizar o sinal.")}finally{setBusy(false)}}
 async function propose(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);const duration=Number(values.get("duration"));const price=String(values.get("price")??"");await update("proposed",{requested_date:values.get("date"),requested_time:values.get("time"),...(duration?{duration_minutes:duration}:{}),...(price?{price_cents:Math.round(Number(price)*100)}:{})})}
 return <div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end",alignItems:"center"}}>{["requested","under_review","proposed"].includes(status)&&<><button aria-label="Confirmar e solicitar sinal" title="Confirma o horário e solicita o sinal" className="pill" disabled={busy} onClick={()=>signal("request")}><Check size={14}/> Confirmar e pedir sinal</button><button aria-label="Recusar" title="Recusar" className="pill" disabled={busy} onClick={()=>update("cancelled_by_professional")}><X size={14}/> Recusar</button><button className="pill" disabled={busy} onClick={()=>setProposing(!proposing)}><CalendarClock size={14}/> Sugerir horário</button>{status==="requested"&&<button className="pill" disabled={busy} onClick={()=>update("under_review")}><Clock3 size={14}/> Analisar</button>}</>}{status==="confirmed"&&paymentStatus==="signal_requested"&&<><span className="pill">Aguardando sinal · 1h</span><button className="pill" disabled={busy} onClick={()=>update("cancelled_by_professional")}><X size={14}/> Cancelar horário</button></>}{status==="confirmed"&&paymentStatus==="signal_reported"&&<button className="pill" disabled={busy} onClick={()=>signal("verify")}><Check size={14}/> Conferir sinal recebido</button>}{status==="confirmed"&&paymentStatus==="partial"&&<button className="pill" disabled={busy} onClick={()=>update("completed")}>Concluir</button>}{status==="confirmed"&&!paymentStatus&&<button className="pill" disabled={busy} onClick={()=>update("completed")}>Concluir</button>}{proposing&&<form onSubmit={propose} className="panel" style={{width:"100%",display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><div className="form-field"><label>Outro dia</label><input name="date" type="date" min={new Date().toLocaleDateString("en-CA")} required/></div><div className="form-field"><label>Horário</label><input name="time" type="time" required/></div><div className="form-field"><label>Duração (min)</label><input name="duration" type="number" min="1" max="1440"/></div><div className="form-field"><label>Valor (R$)</label><input name="price" type="number" min="0" step="0.01"/></div><button className="btn" style={{gridColumn:"1 / -1"}} disabled={busy}>Enviar proposta</button></form>}{error&&<span className="form-error">{error}</span>}</div>;
}
