"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3 } from "lucide-react";
import Link from "next/link";
import { bookingSchema,type BookingInput } from "@/lib/domain";
import { formatDurationDelta, minutesToDuration } from "@/lib/duration";
import { PublicBookingCalendar } from "@/components/public-booking-calendar";
import { PublicWaitlistForm } from "@/components/public-waitlist-form";

type Option={id:string;label:string;price_delta_cents:number;duration_delta_minutes:number};
type Question={id:string;label:string;type:"single_choice"|"multiple_choice"|"text"|"number"|"boolean"|"note";required:boolean;options:Option[]};
type Answer={question_id:string;option_ids:string[];value?:string|number|boolean};
type Quote={price_cents:number|null;duration_minutes:number|null};
function hasAnswer(question:Question,answer:Answer|undefined){
 if(!answer)return false;
 if(question.type==="single_choice"||question.type==="multiple_choice")return answer.option_ids.length>0;
 if(question.type==="boolean")return typeof answer.value==="boolean";
 if(question.type==="number")return typeof answer.value==="number"&&Number.isFinite(answer.value);
 return typeof answer.value==="string"&&answer.value.trim().length>0;
}
export function BookingForm({selectedService,serviceId,slug,basePriceCents,baseDurationMinutes,questions}:{selectedService:string;serviceId:string;slug:string;basePriceCents:number|null;baseDurationMinutes:number|null;questions:Question[]}) {
 const [step,setStep]=useState(0),[answers,setAnswers]=useState<Record<string,Answer>>({}),[quote,setQuote]=useState<Quote>({price_cents:basePriceCents,duration_minutes:baseDurationMinutes}),[error,setError]=useState(""),[trackingUrl,setTrackingUrl]=useState(""),[pending,setPending]=useState(false),[pendingInput,setPendingInput]=useState<BookingInput|null>(null),[unavailableRequest,setUnavailableRequest]=useState<BookingInput|null>(null),[waitlistChoice,setWaitlistChoice]=useState(false),[showBookingConflict,setShowBookingConflict]=useState(false),[openWaitlist,setOpenWaitlist]=useState(false),[date,setDate]=useState(""),[time,setTime]=useState(""),[slots,setSlots]=useState<string[]>([]),[loadingSlots,setLoadingSlots]=useState(false),[bookingWindow,setBookingWindow]=useState<{min_date:string;max_date:string;booking_window:"month"|"year"}|null>(null);
 const answerList=useMemo(()=>questions.map(q=>answers[q.id]??{question_id:q.id,option_ids:[]}),[questions,answers]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{fetch("/api/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,serviceId,answers:answerList})}).then(r=>r.ok?r.json():null).then(data=>{if(active&&data)setQuote(data)}).catch(()=>{});},180);return()=>{active=false;clearTimeout(timer)}},[slug,serviceId,answerList]);
 useEffect(()=>{let active=true;fetch(`/api/availability?slug=${encodeURIComponent(slug)}&window=1`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error();if(active)setBookingWindow(result)}).catch(()=>{});return()=>{active=false}},[slug]);
 useEffect(()=>{if(step!==2||!date)return;let active=true;const timer=setTimeout(()=>{setLoadingSlots(true);setSlots([]);setTime("");const params=new URLSearchParams({slug,serviceId,date,answers:JSON.stringify(answerList)});fetch(`/api/availability?${params}`).then(async r=>{const data=await r.json();if(active&&r.ok)setSlots(data.slots)}).catch(()=>{if(active)setSlots([])}).finally(()=>{if(active)setLoadingSlots(false)})},0);return()=>{active=false;clearTimeout(timer)}},[step,date,slug,serviceId,answerList]);
 function setValue(q:Question,value:Answer){setError("");setAnswers(current=>({...current,[q.id]:value}))}
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const missing=questions.find(q=>q.required&&!hasAnswer(q,answers[q.id]));if(missing){setError(missing.label?`Responda “${missing.label}” para continuar.`:"Uma pergunta obrigatória não foi carregada corretamente. Atualize a página ou avise a profissional.");setStep(1);return}const data=new FormData(event.currentTarget);const parsed=bookingSchema.safeParse({name:data.get("name"),phone:data.get("phone"),serviceId,date,time,note:data.get("note")});if(!parsed.success){setError(parsed.error.issues[0]?.message??"Confira os dados e tente de novo.");return}setPendingInput(parsed.data)}
 async function confirmPhone(){if(!pendingInput)return;setPending(true);setError("");try{const response=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...pendingInput,answers:answerList,slug})});const result=await response.json();if(response.status===409&&(result.code==="SLOT_UNAVAILABLE"||result.code==="WAITLIST_CHOICE")){setUnavailableRequest(pendingInput);setWaitlistChoice(result.code==="WAITLIST_CHOICE");setDate(pendingInput.date);if(result.code==="SLOT_UNAVAILABLE"){setTime("");setSlots(current=>current.filter(slot=>slot!==pendingInput.time));}setPendingInput(null);setStep(2);setShowBookingConflict(true);setError("");return}if(!response.ok)throw new Error(result.error??"Não foi possível enviar sua solicitação.");setTrackingUrl(result.trackingUrl)}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível enviar sua solicitação.")}finally{setPending(false)}}
 function editPhone(){setPendingInput(null);requestAnimationFrame(()=>document.getElementById("phone")?.focus())}
 if(trackingUrl)return <section className="form-card" style={{textAlign:"center"}}><span className="brand-mark" style={{margin:"0 auto",width:48,height:48,fontSize:27}}><Check/></span><span className="eyebrow" style={{display:"block",marginTop:20}}>Solicitação enviada</span><h1>Pronto. Agora é com a profissional.</h1><p>Guarde este link para acompanhar sua solicitação. Você não precisa criar uma conta.</p><Link className="btn" style={{width:"100%"}} href={trackingUrl}>Acompanhar atendimento <ArrowRight size={15}/></Link><Link className="btn secondary" style={{width:"100%",marginTop:10}} href={`/${slug}`}>Voltar à página</Link></section>;  const hasQuestions = questions.length > 0;
  const progressStep = hasQuestions ? step : step === 0 ? 0 : step - 1;
  const stepCount = hasQuestions ? 4 : 3;
  const title = step === 0 ? "Alguns detalhes do serviço" : step === 1 ? "Responda às perguntas" : step === 2 ? "Quando fica melhor?" : "Como podemos falar com você?";
  const previousStep = step === 2 && !hasQuestions ? 0 : step - 1;

  return <>
    {showBookingConflict && unavailableRequest && <div className="capacity-conflict-backdrop"><section className="capacity-conflict-dialog" role="alertdialog" aria-modal="true" aria-labelledby="booking-conflict-title" aria-describedby="booking-conflict-description"><span className="eyebrow">{waitlistChoice?"Interesse neste horário":"Horário indisponível"}</span><h2 id="booking-conflict-title">{waitlistChoice?"Quer entrar na lista de espera?":"Outra cliente pediu esse horário"}</h2><p id="booking-conflict-description">{waitlistChoice?`Já existe uma solicitação para ${unavailableRequest.date} às ${unavailableRequest.time}. Como a profissional ainda não confirmou a outra cliente, você pode escolher entrar na lista de espera para este horário. A profissional verá seu interesse e falará com você se puder atender.`:`O horário de ${unavailableRequest.date} às ${unavailableRequest.time} acabou de ficar indisponível. Escolha outro horário ou entre na lista de espera para este serviço e horário.`}</p><div className="waitlist-actions"><button className="btn" type="button" onClick={() => { setShowBookingConflict(false); setOpenWaitlist(true); document.getElementById("public-waitlist-form")?.scrollIntoView({ behavior: "smooth", block: "center" }); }}>{waitlistChoice?"Sim, entrar na lista":"Entrar na lista de espera"}</button><button className="btn secondary" type="button" onClick={() => { setShowBookingConflict(false); setTime(""); }}>{waitlistChoice?"Escolher outro horário":"Voltar ao calendário"}</button></div></section></div>}
    <form className="form-card" onSubmit={submit}>
      <span className="eyebrow">Vamos montar seu atendimento</span><h1>{title}</h1>
      <div className="progress-steps">{Array.from({ length: stepCount }, (_, index) => <span className={progressStep >= index ? "on" : ""} key={index} />)}</div>
      <div className="pill"><span>{selectedService}</span><span style={{ marginLeft: 8 }}>· {quote.price_cents === null ? "a combinar" : `${basePriceCents === null ? "a partir de " : ""}R$ ${(quote.price_cents / 100).toFixed(2).replace(".", ",")}`}</span></div>
      {step === 0 && <><p>Confira o serviço e a estimativa antes de continuar.</p><div className="calendar-art" style={{ width: "100%" }}><div className="cal-line"><b>Estimativa</b><b>{quote.price_cents === null ? "A combinar" : `R$ ${(quote.price_cents / 100).toFixed(2).replace(".", ",")}`}</b></div><div className="cal-line"><span><Clock3 size={12} /> Duração aproximada</span><b>{quote.duration_minutes ? minutesToDuration(quote.duration_minutes) : "A combinar"}</b></div></div></>}
      {step === 1 && <><p>Responda às perguntas para calcular a estimativa do atendimento.</p>{questions.map(question => {
        const answer = answers[question.id] ?? { question_id: question.id, option_ids: [] };
        return <div className="form-field" key={question.id}><label>{question.label}{question.required ? " *" : ""}</label>
          {question.type === "single_choice" && question.options.map((option, index) => <label className="service-card" key={option.id} style={{ marginTop: 7, cursor: "pointer" }}><input type="radio" name={question.id} required={question.required && index === 0} checked={answer.option_ids.includes(option.id)} onChange={() => setValue(question, { ...answer, option_ids: [option.id] })} /><span className="service-text"><b>{option.label}</b>{(option.price_delta_cents || option.duration_delta_minutes !== 0) && <small>{option.price_delta_cents ? `${option.price_delta_cents > 0 ? "+" : "−"} R$ ${(Math.abs(option.price_delta_cents) / 100).toFixed(2).replace(".", ",")}` : ""}{option.duration_delta_minutes ? ` · ${formatDurationDelta(option.duration_delta_minutes)}` : ""}</small>}</span></label>)}
          {question.type === "multiple_choice" && question.options.map(option => <label className="service-card" key={option.id} style={{ marginTop: 7, cursor: "pointer" }}><input type="checkbox" checked={answer.option_ids.includes(option.id)} onChange={() => setValue(question, { ...answer, option_ids: answer.option_ids.includes(option.id) ? answer.option_ids.filter(id => id !== option.id) : [...answer.option_ids, option.id] })} /><span className="service-text"><b>{option.label}</b><small>{option.price_delta_cents ? `${option.price_delta_cents > 0 ? "+" : "−"} R$ ${(Math.abs(option.price_delta_cents) / 100).toFixed(2).replace(".", ",")}` : ""}{option.duration_delta_minutes ? ` · ${formatDurationDelta(option.duration_delta_minutes)}` : ""}</small></span></label>)}
          {question.type === "boolean" && <select value={answer.value === undefined ? "" : String(answer.value)} onChange={event => setValue(question, { ...answer, value: event.target.value === "true" })} required={question.required}><option value="">Escolha</option><option value="true">Sim</option><option value="false">Não</option></select>}
          {question.type === "note" && <textarea rows={3} maxLength={1000} required={question.required} value={String(answer.value ?? "")} onChange={event => setValue(question, { ...answer, value: event.target.value })} />}
          {(question.type === "text" || question.type === "number") && <input type={question.type === "number" ? "number" : "text"} required={question.required} value={String(answer.value ?? "")} onChange={event => setValue(question, { ...answer, value: question.type === "number" ? (event.target.value === "" ? undefined : Number(event.target.value)) : event.target.value })} />}
        </div>;
      })}<div className="calendar-art" style={{ width: "100%" }}><div className="cal-line"><b>Estimativa atualizada</b><b>{quote.price_cents === null ? "A combinar" : `R$ ${(quote.price_cents / 100).toFixed(2).replace(".", ",")}`}</b></div><div className="cal-line"><span><Clock3 size={12} /> Duração aproximada</span><b>{quote.duration_minutes ? minutesToDuration(quote.duration_minutes) : "A combinar"}</b></div></div></>}
      {step === 2 && <><p>Os horários consideram a duração do serviço e a agenda da profissional.</p><div className="form-field"><label>Dia disponível</label><PublicBookingCalendar key={`${serviceId}:${JSON.stringify(answerList)}`} slug={slug} serviceId={serviceId} answers={answerList} minDate={bookingWindow?.min_date} maxDate={bookingWindow?.max_date} value={date} onChange={value => { setDate(value); setError(""); }} /><small>{bookingWindow?.booking_window === "year" ? "Calendário aberto até o fim do ano atual." : "Calendário aberto somente para o mês atual."}</small></div><div className="form-field"><label htmlFor="time">Horário</label><select id="time" required value={time} onChange={event => { setTime(event.target.value); setError(""); }} disabled={!date || loadingSlots}><option value="">{loadingSlots ? "Buscando horários…" : date ? "Escolha um horário" : "Selecione um dia disponível"}</option>{slots.map(slot => <option value={slot} key={slot}>{slot}</option>)}</select>{date && !loadingSlots && !slots.length && <small style={{ color: "var(--muted)" }}>Nenhum horário disponível neste dia. Tente outra data.</small>}</div></>}
      {step === 3 && <><p>Essas informações servem para a profissional responder sobre seu atendimento.</p><input type="hidden" name="date" value={date} /><input type="hidden" name="time" value={time} /><div className="form-field"><label htmlFor="name">Seu nome</label><input id="name" name="name" placeholder="Como você gosta de ser chamada?" minLength={2} required /></div><div className="form-field"><label htmlFor="phone">WhatsApp com DDD</label><input id="phone" name="phone" type="tel" placeholder="(71) 99999-9999" required /></div><div className="form-field"><label htmlFor="note">Quer contar mais alguma coisa? (opcional)</label><textarea id="note" name="note" rows={3} maxLength={500} placeholder="Uma observação para a profissional" /></div></>}
      {pendingInput && <div className="trial-box" role="group" aria-label="Confirme seu WhatsApp" style={{ marginTop: 18 }}><b>Confirme seu WhatsApp</b><p>Vamos enviar a solicitação usando <strong>{pendingInput.phone}</strong>. Esse número está correto?</p><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button type="button" className="btn" onClick={confirmPhone} disabled={pending}>Sim, enviar solicitação</button><button type="button" className="btn secondary" onClick={editPhone} disabled={pending}>Corrigir número</button></div></div>}
      {error && <p className="form-error" role="alert">{error}</p>}
      <div style={{ display: "flex", gap: 10, marginTop: 22 }}>{step > 0 && <button type="button" className="btn secondary" onClick={() => { setError(""); setPendingInput(null); setStep(previousStep); }}><ArrowLeft size={15} /> Voltar</button>}{step < 3 ? <button type="button" className="btn" style={{ flex: 1 }} onClick={() => {
        if (step === 1) { const missing = questions.find(question => question.required && !hasAnswer(question, answers[question.id])); if (missing) { setError(missing.label ? `Responda “${missing.label}” para continuar.` : "Uma pergunta obrigatória não foi carregada corretamente. Atualize a página ou avise a profissional."); return; } }
        if (step === 2 && (!date || !time)) { setError(!date ? "Escolha um dia para continuar." : "Escolha um horário disponível."); return; }
        setError(""); setStep(step === 0 && !hasQuestions ? 2 : step + 1);
      }}>Continuar <ArrowRight size={15} /></button> : !pendingInput && <button className="btn" style={{ flex: 1 }} disabled={pending}>{pending ? "Verificando…" : "Enviar solicitação"} <ArrowRight size={15} /></button>}</div>
      <p style={{ fontSize: 10, lineHeight: 1.5, color: "var(--muted)" }}>Ao enviar, você concorda com nossos <Link href="/termos" style={{ textDecoration: "underline" }}>Termos</Link> e a <Link href="/privacidade" style={{ textDecoration: "underline" }}>Política de Privacidade</Link>.</p>
    </form>
    {step === 2 && <PublicWaitlistForm slug={slug} serviceId={serviceId} selectedDate={unavailableRequest?.date || date} selectedTime={unavailableRequest?.time} initialName={unavailableRequest?.name} initialPhone={unavailableRequest?.phone} startOpen={openWaitlist} onClose={() => setOpenWaitlist(false)} />}
  </>;
}
