"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, X, CalendarClock } from "lucide-react";

export function BookingControls({token,status,slug,service}:{token:string;status:string;slug:string;service:string}){
 const router=useRouter();const [date,setDate]=useState("");const [time,setTime]=useState("");const [slots,setSlots]=useState<string[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [choosing,setChoosing]=useState(false);
 async function loadSlots(value:string){setDate(value);setTime("");setMessage("");if(!value)return;const params=new URLSearchParams({slug,service,date:value});try{const response=await fetch(`/api/availability?${params}`);const result=await response.json();setSlots(result.slots??[])}catch{setSlots([])}}
 async function act(action:"accept"|"cancel"|"request_another_time"){setBusy(true);setMessage("");try{const response=await fetch(`/api/booking/${token}/action`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,date:action==="request_another_time"?date:undefined,time:action==="request_another_time"?time:undefined})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Não foi possível atualizar o atendimento.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível atualizar o atendimento.")}finally{setBusy(false)}}
 const canCancel=["requested","under_review","proposed","confirmed"].includes(status);
 return <div style={{marginTop:22}}>{status==="proposed"&&<><p style={{fontSize:13,color:"var(--muted)"}}>A profissional sugeriu este horário. Você pode aceitar ou pedir outro.</p><button className="btn" style={{width:"100%"}} disabled={busy} onClick={()=>act("accept")}><Check size={15}/> Aceitar horário</button><button className="btn secondary" style={{width:"100%",marginTop:9}} onClick={()=>setChoosing(!choosing)}><CalendarClock size={15}/> Escolher outro horário</button>{choosing&&<div className="trial-box" style={{marginTop:12}}><div className="form-field"><label htmlFor="alternate-date">Outro dia</label><input id="alternate-date" type="date" min={new Date().toLocaleDateString("en-CA")} value={date} onChange={event=>loadSlots(event.target.value)}/></div><div className="form-field"><label htmlFor="alternate-time">Horário disponível</label><select id="alternate-time" value={time} onChange={event=>setTime(event.target.value)}><option value="">Selecione</option>{slots.map(slot=><option key={slot} value={slot}>{slot}</option>)}</select></div><button className="btn" disabled={busy||!time} onClick={()=>act("request_another_time")}>Pedir este horário</button></div>}</>}{canCancel&&<button className="btn secondary" style={{width:"100%",marginTop:9}} disabled={busy} onClick={()=>act("cancel")}><X size={15}/> Cancelar solicitação</button>}{message&&<p className="form-error" role="alert">{message}</p>}</div>;
}
