"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3 } from "lucide-react";
import Link from "next/link";
import { bookingSchema,type BookingInput } from "@/lib/domain";
import { formatDurationDelta, minutesToDuration } from "@/lib/duration";
import { PublicBookingCalendar } from "@/components/public-booking-calendar";
import { PublicWaitlistForm } from "@/components/public-waitlist-form";

type Option={id:string;label:string;price_delta_cents:number;duration_delta_minutes:number};
type Question={id:string;label:string;type:"single_choice"|"multiple_choice"|"text"|"number"|"boolean"|"note";required:boolean;options:Option[]};
type Answer={question_id:string;option_ids:string[];value?:string|number|boolean};
type Quote={price_cents:number|null;duration_minutes:number|null};
export function BookingForm({selectedService,serviceId,slug,basePriceCents,baseDurationMinutes,questions}:{selectedService:string;serviceId:string;slug:string;basePriceCents:number|null;baseDurationMinutes:number|null;questions:Question[]}) {
 const [step,setStep]=useState(0),[answers,setAnswers]=useState<Record<string,Answer>>({}),[quote,setQuote]=useState<Quote>({price_cents:basePriceCents,duration_minutes:baseDurationMinutes}),[error,setError]=useState(""),[trackingUrl,setTrackingUrl]=useState(""),[pending,setPending]=useState(false),[pendingInput,setPendingInput]=useState<BookingInput|null>(null),[unavailableRequest,setUnavailableRequest]=useState<BookingInput|null>(null),[showBookingConflict,setShowBookingConflict]=useState(false),[openWaitlist,setOpenWaitlist]=useState(false),[date,setDate]=useState(""),[time,setTime]=useState(""),[slots,setSlots]=useState<string[]>([]),[loadingSlots,setLoadingSlots]=useState(false),[bookingWindow,setBookingWindow]=useState<{min_date:string;max_date:string;booking_window:"month"|"year"}|null>(null);
 const answerList=useMemo(()=>questions.map(q=>answers[q.id]??{question_id:q.id,option_ids:[]}),[questions,answers]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{fetch("/api/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,serviceId,answers:answerList})}).then(r=>r.ok?r.json():null).then(data=>{if(active&&data)setQuote(data)}).catch(()=>{});},180);return()=>{active=false;clearTimeout(timer)}},[slug,serviceId,answerList]);
 useEffect(()=>{let active=true;fetch(`/api/availability?slug=${encodeURIComponent(slug)}&window=1`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error();if(active)setBookingWindow(result)}).catch(()=>{});return()=>{active=false}},[slug]);
 useEffect(()=>{if(step!==1||!date)return;let active=true;const timer=setTimeout(()=>{setLoadingSlots(true);setSlots([]);setTime("");const params=new URLSearchParams({slug,serviceId,date,answers:JSON.stringify(answerList)});fetch(`/api/availability?${params}`).then(async r=>{const data=await r.json();if(active&&r.ok)setSlots(data.slots)}).catch(()=>{if(active)setSlots([])}).finally(()=>{if(active)setLoadingSlots(false)})},0);return()=>{active=false;clearTimeout(timer)}},[step,date,slug,serviceId,answerList]);
 function setValue(q:Question,value:Answer){setAnswers(current=>({...current,[q.id]:value}))}
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");for(const q of questions){const a=answers[q.id];if(q.required&&(!a||(q.options.length?a.option_ids.length===0:a.value===undefined||a.value===""))){setError(`Responda: ${q.label}`);setStep(0);return}}const data=new FormData(event.currentTarget);const parsed=bookingSchema.safeParse({name:data.get("name"),phone:data.get("phone"),serviceId,date,time,note:data.get("note")});if(!parsed.success){setError(parsed.error.issues[0]?.message??"Confira os dados e tente de novo.");return}setPendingInput(parsed.data)}
 async function confirmPhone(){if(!pendingInput)return;setPending(true);setError("");try{const response=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...pendingInput,answers:answerList,slug})});const result=await response.json();if(response.status===409&&result.code==="SLOT_UNAVAILABLE"){setUnavailableRequest(pendingInput);setDate(pendingInput.date);setTime("");setSlots(current=>current.filter(slot=>slot!==pendingInput.time));setPendingInput(null);setStep(1);setShowBookingConflict(true);setError("");return}if(!response.ok)throw new Error(result.error??"Não foi possível enviar sua solicitação.");setTrackingUrl(result.trackingUrl)}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível enviar sua solicitação.")}finally{setPending(false)}}
 function editPhone(){setPendingInput(null);requestAnimationFrame(()=>document.getElementById("phone")?.focus())}
 if(trackingUrl)return <section className="form-card" style={{textAlign:"center"}}><span className="brand-mark" style={{margin:"0 auto",width:48,height:48,fontSize:27}}><Check/></span><span className="eyebrow" style={{display:"block",marginTop:20}}>Solicitação enviada</span><h1>Pronto. Agora é com a profissional.</h1><p>Guarde este link para acompanhar sua solicitação. Você não precisa criar uma conta.</p><Link className="btn" style={{width:"100%"}} href={trackingUrl}>Acompanhar atendimento <ArrowRight size={15}/></Link><Link className="btn secondary" style={{width:"100%",marginTop:10}} href={`/${slug}`}>Voltar à página</Link></section>;
 return <>{showBookingConflict&&unavailableRequest&&<div className="capacity-conflict-backdrop"><section className="capacity-conflict-dialog" role="alertdialog" aria-modal="true" aria-labelledby="booking-conflict-title" aria-describedby="booking-conflict-description"><span className="eyebrow">Horário indisponível</span><h2 id="booking-conflict-title">Outra cliente pediu esse horário</h2><p id="booking-conflict-description">O horário de {unavailableRequest.date} às {unavailableRequest.time} acabou de receber uma solicitação e não pode ser enviado novamente. Escolha outra opção ou entre na lista de espera para esse serviço e horário.</p><div className="waitlist-actions"><button className="btn" type="button" onClick={()=>{setShowBookingConflict(false);setOpenWaitlist(true);document.getElementById("public-waitlist-form")?.scrollIntoView({behavior:"smooth",block:"center"})}}>Entrar na lista de espera</button><button className="btn secondary" type="button" onClick={()=>setShowBookingConflict(false)}>Escolher outro horário</button></div></section></div>}<form className="form-card" onSubmit={submit}><span className="eyebrow">Vamos montar seu atendimento</span><h1>{step===0?"Alguns detalhes do serviço":step===1?"Quando fica melhor?":"Como podemos falar com você?"}</h1><div className="progress-steps">{[0,1,2].map(index=><span className={step>=index?"on":""} key={index}/>)}</div><div className="pill"><span>{selectedService}</span><span style={{marginLeft:8}}>· {quote.price_cents===null?"a combinar":`${basePriceCents===null?"a partir de ":""}R$ ${(quote.price_cents/100).toFixed(2).replace(".",",")}`}</span></div>
 {pendingInput&&<div className="trial-box" role="group" aria-label="Confirme seu WhatsApp" style={{marginTop:18}}><b>Confirme seu WhatsApp</b><p>Vamos enviar a solicitação usando <strong>{pendingInput.phone}</strong>. Esse número está correto?</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" className="btn" onClick={confirmPhone} disabled={pending}>Sim, enviar solicitação</button><button type="button" className="btn secondary" onClick={editPhone} disabled={pending}>Corrigir número</button></div></div>}{error&&<p className="form-error" role="alert">{error}</p>}<div style={{display:"flex",gap:10,marginTop:22}}>{step>0&&<button type="button" className="btn secondary" onClick={()=>setStep(step-1)}><ArrowLeft size={15}/> Voltar</button>}{step<2?<button type="button" className="btn" style={{flex:1}} onClick={()=>{if(step===0&&questions.some(q=>q.required&&!answers[q.id])){setError("Responda às perguntas obrigatórias para continuar.");return}if(step===1&&(!date||!time)){setError(!date?"Escolha um dia para continuar.":"Escolha um horário disponível.");return}setError("");setStep(step+1)}}>Continuar <ArrowRight size={15}/></button>:!pendingInput&&<button className="btn" style={{flex:1}} disabled={pending}>{pending?"Verificando…":"Enviar solicitação"} <ArrowRight size={15}/></button>}</div><p style={{fontSize:10,lineHeight:1.5,color:"var(--muted)"}}>Ao enviar, você concorda com nossos <Link href="/termos" style={{textDecoration:"underline"}}>Termos</Link> e a <Link href="/privacidade" style={{textDecoration:"underline"}}>Política de Privacidade</Link>.</p></form>{step===1&&<PublicWaitlistForm slug={slug} serviceId={serviceId} selectedDate={unavailableRequest?.date||date} selectedTime={unavailableRequest?.time} initialName={unavailableRequest?.name} initialPhone={unavailableRequest?.phone} startOpen={openWaitlist} onClose={()=>setOpenWaitlist(false)}/>}</>;
}
