"use client";

import { useEffect, useState } from "react";
import { Check, Clock3 } from "lucide-react";

type Settings={pix_key:string;pix_holder:string;signal_type:"fixed"|"percent";signal_amount:number};
const empty:Settings={pix_key:"",pix_holder:"",signal_type:"fixed",signal_amount:0};

export function BusinessPixSettings(){
 const [settings,setSettings]=useState(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;fetch("/api/business/pix",{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);if(active)setSettings({...empty,...result})}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Não foi possível carregar as configurações do Pix.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage("");try{const response=await fetch("/api/business/pix",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage("Configuração do Pix salva.")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível salvar.")}finally{setSaving(false)}}
 return <section className="panel" style={{maxWidth:800,marginTop:16}}><h2 className="serif" style={{fontSize:26}}>Pix e sinal</h2><p>A cliente paga o sinal diretamente para você. O sistema não confirma o pagamento automaticamente: confira o extrato antes de confirmar o atendimento.</p>{loading?<p><Clock3 size={14}/> Carregando...</p>:<form onSubmit={save}><div className="form-field"><label htmlFor="business-pix-holder">Nome do titular da chave</label><input id="business-pix-holder" value={settings.pix_holder} onChange={event=>setSettings(current=>({...current,pix_holder:event.target.value}))} maxLength={120} placeholder="Nome que aparece no banco"/></div><div className="form-field"><label htmlFor="business-pix-key">Chave Pix</label><input id="business-pix-key" value={settings.pix_key} onChange={event=>setSettings(current=>({...current,pix_key:event.target.value}))} maxLength={200} placeholder="CPF, CNPJ, e-mail, telefone ou chave aleatória"/></div><div className="stats" style={{gridTemplateColumns:"minmax(0,1fr) minmax(140px,.7fr)"}}><div className="form-field"><label htmlFor="business-signal-type">Como calcular o sinal</label><select id="business-signal-type" value={settings.signal_type} onChange={event=>setSettings(current=>({...current,signal_type:event.target.value as Settings["signal_type"]}))}><option value="fixed">Valor fixo</option><option value="percent">Porcentagem do atendimento</option></select></div><div className="form-field"><label htmlFor="business-signal-amount">{settings.signal_type==="fixed"?"Sinal em reais":"Sinal em %"}</label><input id="business-signal-amount" type="number" min="0" max={settings.signal_type==="percent"?100:100000} step="0.01" value={settings.signal_amount||""} onChange={event=>setSettings(current=>({...current,signal_amount:Number(event.target.value)||0}))} placeholder={settings.signal_type==="fixed"?"Ex.: 50,00":"Ex.: 20"}/></div></div><button className="btn" type="submit" disabled={saving}>{saving?<Clock3 size={15}/>:<Check size={15}/>} {saving?"Salvando...":"Salvar configuração do Pix"}</button>{message&&<p className={message.startsWith("Não")?"form-error":"trial-box"} role="status">{message}</p>}</form>}<p className="demo-disclaimer">Para solicitar sinal, cadastre chave e titular e defina um valor maior que zero. Os dados bancários só são mostrados à cliente depois da aprovação.</p></section>;
}
