"use client";
import { BrandLogo } from "@/components/brand-logo";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, CreditCard, House, Image as ImageIcon, Inbox, MapPin, Plus, Scissors, Settings, Trash2, Users, X } from "lucide-react";

type Section="inicio"|"agenda"|"cliente"|"solicitacoes"|"clientes"|"servicos"|"perguntas"|"financeiro"|"portfolio"|"minha-pagina"|"configuracoes"|"bloqueios"|"assinatura";
type QuestionOption={id:string;label:string;price:number;minutes:number};
type CustomerQuestion={id:string;label:string;kind:"text"|"single"|"multiple"|"yesno";required:boolean;options:QuestionOption[];serviceIds:string[]};
type Service={id:string;name:string;price:number;duration:number;active:boolean;description:string;images:string[];questionIds:string[]};
type DemoAppointment={id:string;day:string;time:string;client:string;phone:string;serviceId:string;status:string;price:number;duration:number;answers:{question:string;value:string}[]};
type Hour={day:string;enabled:boolean;start:string;lunchStart:string;lunchEnd:string;end:string};
type AgendaBlock={id:string;day:string;start:string;end:string;label:string};
type DemoData={displayName:string;business:string;whatsapp:string;city:string;slug:string;description:string;services:Service[];questions:CustomerQuestion[];hours:Hour[];appointments:DemoAppointment[];blocks:AgendaBlock[]};
const KEY="ta-marcado-demo-v1";
const weekdays=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
const uid=()=>crypto.randomUUID();
const dateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const dateFromKey=(key:string)=>{const [y,m,d]=key.split("-").map(Number);return new Date(y,m-1,d,12)};
const offsetDate=(offset:number)=>{const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()+offset);return dateKey(date)};
const money=(cents:number)=>`R$ ${(cents/100).toFixed(2).replace(".",",")}`;
const prettyDate=(key:string,options:Intl.DateTimeFormatOptions={weekday:"long",day:"numeric",month:"long"})=>new Intl.DateTimeFormat("pt-BR",options).format(dateFromKey(key));
const defaultHours:Hour[]=weekdays.map((day,index)=>({day,enabled:index>0&&index<6,start:"09:00",lunchStart:"12:00",lunchEnd:"13:00",end:"18:00"}));
const starterServices:Service[]=[{id:"s-box",name:"Box braids",price:22000,duration:240,active:true,description:"Tranças feitas com cuidado e atenção aos detalhes.",images:[],questionIds:["q-length","q-material"]},{id:"s-nago",name:"Nagô",price:10000,duration:120,active:true,description:"",images:[],questionIds:["q-length"]},{id:"s-twist",name:"Twist",price:18000,duration:180,active:true,description:"",images:[],questionIds:[]}];
const starterQuestions:CustomerQuestion[]=[{id:"q-length",label:"Qual comprimento você prefere?",kind:"single",required:true,serviceIds:["s-box","s-nago"],options:[{id:"o-short",label:"Curto",price:0,minutes:0},{id:"o-long",label:"Longo",price:4000,minutes:60}]},{id:"q-material",label:"Quem fornece o material?",kind:"single",required:true,serviceIds:["s-box"],options:[{id:"o-client",label:"Eu levo",price:0,minutes:0},{id:"o-pro",label:"A profissional fornece",price:4000,minutes:0}]}];
function defaultData():DemoData{return{displayName:"Ana Martins",business:"Ana Tranças",whatsapp:"(71) 99999-1234",city:"Rio Vermelho, Salvador",slug:"ana-trancas",description:"Tranças feitas com carinho e atenção a cada detalhe. Vamos encontrar o estilo ideal para você?",services:starterServices,questions:starterQuestions,hours:defaultHours,blocks:[],appointments:[{id:"demo-1",day:offsetDate(0),time:"14:00",client:"Camila Santos",phone:"(71) 98888-1001",serviceId:"s-box",status:"Confirmado",price:22000,duration:240,answers:[{question:"Qual comprimento você prefere?",value:"Longo"},{question:"Quem fornece o material?",value:"Eu levo"}]},{id:"demo-2",day:offsetDate(1),time:"09:30",client:"Júlia Oliveira",phone:"(71) 98888-1002",serviceId:"s-nago",status:"Confirmado",price:10000,duration:120,answers:[]},{id:"demo-3",day:offsetDate(3),time:"11:00",client:"Mariana Costa",phone:"(71) 98888-1003",serviceId:"s-twist",status:"Nova solicitação",price:18000,duration:180,answers:[]}]};}
const initial=defaultData();
const nav:{id:Section;label:string;icon:typeof House}[]=[{id:"inicio",label:"Início",icon:House},{id:"agenda",label:"Agenda",icon:CalendarDays},{id:"solicitacoes",label:"Solicitações",icon:Inbox},{id:"clientes",label:"Clientes",icon:Users},{id:"servicos",label:"Serviços",icon:Scissors},{id:"perguntas",label:"Perguntas para clientes",icon:Inbox},{id:"financeiro",label:"Financeiro",icon:CircleDollarSign},{id:"portfolio",label:"Portfólio",icon:ImageIcon},{id:"minha-pagina",label:"Minha página",icon:MapPin},{id:"configuracoes",label:"Configurações",icon:Settings},{id:"bloqueios",label:"Bloqueio de agenda",icon:X},{id:"assinatura",label:"Assinatura",icon:CreditCard}];
function normalizeData(raw:Record<string,unknown>):DemoData{
 const defaults=defaultData();
 const oldServices=(raw.services as Record<string,unknown>[]|undefined)??(defaults.services as unknown as Record<string,unknown>[]);
 const services:Service[]=oldServices.map((item,index)=>{const oldQuestions=Array.isArray(item.questions)?item.questions as Record<string,unknown>[]:[];const name=String(item.name??"Serviço"),starterId=starterServices.find(s=>s.name===name)?.id;return{id:String(item.id??starterId??`legacy-service-${index}`),name,price:Number(item.price??0)<10000?Number(item.price??0)*100:Number(item.price??0),duration:Number(item.duration??120),active:item.active!==false,description:String(item.description??""),images:Array.isArray(item.images)?item.images as string[]:typeof item.image==="string"?[item.image]:[],questionIds:Array.isArray(item.questionIds)?item.questionIds as string[]:oldQuestions.map((_,qi)=>`legacy-q-${index}-${qi}`)}});
 const questions:CustomerQuestion[]=(raw.questions as CustomerQuestion[]|undefined)??oldServices.flatMap((item,index)=>{const old=Array.isArray(item.questions)?item.questions as Record<string,unknown>[]:[];return old.map((q,qi)=>({id:`legacy-q-${index}-${qi}`,label:String(q.label??"Pergunta"),kind:(q.kind??q.type)==="multiple"||q.type==="multiple_choice"?"multiple":(q.kind??q.type)==="single_choice"?"single":(q.kind??"text") as CustomerQuestion["kind"],required:q.required!==false,serviceIds:[services[index]?.id??""],options:(q.options as Record<string,unknown>[]|undefined??[]).map((o,oi)=>({id:String(o.id??`lo-${index}-${qi}-${oi}`),label:String(o.label??"Opção"),price:Number(o.price??Number(o.priceDelta??0)*100),minutes:Number(o.minutes??o.durationDelta??0)}))}))});
 const rawAppointments=(raw.appointments as Record<string,unknown>[]|undefined)??(defaults.appointments as unknown as Record<string,unknown>[]);
 const appointments=rawAppointments.map((item,index)=>{const service=services.find(s=>s.name===item.service)||services[0];const day=typeof item.day==="string"?item.day:offsetDate(Number(item.dayOffset??index));return{id:String(item.id??uid()),day,time:String(item.time??"09:00"),client:String(item.client??"Cliente"),phone:String(item.phone??""),serviceId:String(item.serviceId??service?.id??""),status:String(item.status??"Nova solicitação"),price:Number(item.price??service?.price??0),duration:Number(item.duration??service?.duration??60),answers:(item.answers as DemoAppointment["answers"]|undefined)??[]}});
 const rawHours=raw.hours as Record<string,unknown>[]|undefined;
 return{...defaults,...raw,services,questions,hours:rawHours?weekdays.map(day=>{const old=rawHours.find(h=>h.day===day);return{day,enabled:old?.enabled===true,start:String(old?.start??"09:00"),lunchStart:String(old?.lunchStart??"12:00"),lunchEnd:String(old?.lunchEnd??"13:00"),end:String(old?.end??"18:00")}}):defaults.hours,appointments,blocks:(raw.blocks as AgendaBlock[]|undefined)??[],displayName:String(raw.displayName??defaults.displayName),business:String(raw.business??defaults.business),whatsapp:String(raw.whatsapp??defaults.whatsapp),city:String(raw.city??defaults.city),slug:String(raw.slug??defaults.slug),description:String(raw.description??defaults.description)};
}
function timeMinutes(value:string){const [h,m]=value.split(":").map(Number);return h*60+m;}
function calendarDays(month:Date){const first=new Date(month.getFullYear(),month.getMonth(),1,12),last=new Date(month.getFullYear(),month.getMonth()+1,0,12),start=new Date(first);start.setDate(1-first.getDay());return Array.from({length:Math.ceil((first.getDay()+last.getDate())/7)*7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d;});}
function Panel({title,children,aside}:{title:string;children:React.ReactNode;aside?:React.ReactNode}){return <section className="panel" style={{marginBottom:16}}><div className="panel-title">{title}{aside}</div>{children}</section>}

export function DemoWorkspace(){
 const [section,setSection]=useState<Section>("inicio"),[data,setData]=useState(initial),[ready,setReady]=useState(false),[saved,setSaved]=useState(false);
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1,12)),[selectedDay,setSelectedDay]=useState(""),[bookingDay,setBookingDay]=useState(""),[clientService,setClientService]=useState(starterServices[0].id),[clientName,setClientName]=useState(""),[clientPhone,setClientPhone]=useState(""),[clientAnswers,setClientAnswers]=useState<Record<string,string>>({}),[clientSuccess,setClientSuccess]=useState("");
 const [newService,setNewService]=useState(""),[blockDay,setBlockDay]=useState(offsetDate(1)),[blockStart,setBlockStart]=useState("12:00"),[blockEnd,setBlockEnd]=useState("13:00"),[portfolioService,setPortfolioService]=useState(starterServices[0].id),[notice,setNotice]=useState("");
 useEffect(()=>{try{const stored=localStorage.getItem(KEY);if(stored)setData(normalizeData(JSON.parse(stored)))}catch{}setReady(true);const sync=(event:StorageEvent)=>{if(event.key===KEY&&event.newValue){try{setData(normalizeData(JSON.parse(event.newValue)))}catch{}}};window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync)},[]);
 useEffect(()=>{if(ready){localStorage.setItem(KEY,JSON.stringify(data));setSaved(true);const timer=setTimeout(()=>setSaved(false),1200);return()=>clearTimeout(timer)}},[data,ready]);
 const days=useMemo(()=>calendarDays(month),[month]);
 const titles:Record<Section,string>={inicio:"Bom dia, Ana ☀️",agenda:"Agenda",cliente:"Agendar como cliente",solicitacoes:"Solicitações",clientes:"Clientes",servicos:"Seus serviços",perguntas:"Perguntas para clientes",financeiro:"Financeiro",portfolio:"Portfólio", "minha-pagina":"Sua página pública",configuracoes:"Configurações do espaço",bloqueios:"Bloqueio de agenda",assinatura:"Seu plano"};
 const selectedService=data.services.find(s=>s.id===clientService&&s.active)??data.services.find(s=>s.active);
 const customerQuestions=data.questions.filter(q=>selectedService?.questionIds.includes(q.id));
 const customers=useMemo(()=>{const map=new Map<string,{phone:string;name:string;visits:DemoAppointment[]}>();for(const a of data.appointments){const digits=a.phone.replace(/\D/g,"");if(!digits)continue;const current=map.get(digits)??{phone:a.phone,name:a.client,visits:[]};current.visits.push(a);map.set(digits,current)}return Array.from(map.values())},[data.appointments]);
 function appointmentsOn(day:string){return data.appointments.filter(a=>a.day===day&&a.status!=="Recusado"&&a.status!=="Cancelado").sort((a,b)=>a.time.localeCompare(b.time));}
 function slotsOn(day:string,service:Service,duration=service.duration){const weekday=dateFromKey(day).getDay(),hours=data.hours.find(h=>weekdays.indexOf(h.day)===weekday);if(!hours?.enabled)return[];const ranges=[[timeMinutes(hours.start),timeMinutes(hours.lunchStart)],[timeMinutes(hours.lunchEnd),timeMinutes(hours.end)]].filter(([a,b])=>b>a);const occupied=appointmentsOn(day).filter(a=>a.status==="Confirmado").map(a=>[timeMinutes(a.time),timeMinutes(a.time)+(a.duration||data.services.find(s=>s.id===a.serviceId)?.duration||60)]);const blocks=data.blocks.filter(b=>b.day===day).map(b=>[timeMinutes(b.start),timeMinutes(b.end)]);const result:string[]=[];for(const [from,to] of ranges)for(let n=from;n+duration<=to;n+=30)if(!occupied.some(([a,b])=>n<b&&n+duration>a)&&!blocks.some(([a,b])=>n<b&&n+duration>a))result.push(`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`);return result;}
 const quote=useMemo(()=>{let price=selectedService?.price??0,duration=selectedService?.duration??0;for(const question of customerQuestions){const chosen=(clientAnswers[question.id]??"").split(", ");for(const option of question.options)if(chosen.includes(option.label)){price+=option.price;duration+=option.minutes;}}return{price,duration}},[selectedService,customerQuestions,clientAnswers]);
 function openBooking(day:string){setBookingDay(day);setClientSuccess("");setClientAnswers({});setSection("cliente");}
 function submitBooking(){if(!bookingDay||!selectedService||!clientName.trim()||clientPhone.replace(/\D/g,"").length<10||!clientAnswers.__time)return;const answers=customerQuestions.map(q=>({question:q.label,value:clientAnswers[q.id]??""}));for(const q of customerQuestions)if(q.required&&!clientAnswers[q.id]?.trim()){setNotice(`Responda à pergunta: ${q.label}`);return;}let price=selectedService.price,duration=selectedService.duration;for(const q of customerQuestions){const value=clientAnswers[q.id];for(const option of q.options)if(value?.split(", ").includes(option.label)){price+=option.price;duration+=option.minutes;}}const appointment:DemoAppointment={id:uid(),day:bookingDay,time:clientAnswers.__time,client:clientName.trim(),phone:clientPhone.trim(),serviceId:selectedService.id,status:"Nova solicitação",price,duration,answers};setData(current=>({...current,appointments:[...current.appointments,appointment]}));setSelectedDay(bookingDay);setClientSuccess(`Pedido enviado para ${prettyDate(bookingDay)} às ${appointment.time}.`);setBookingDay("");setClientAnswers({});setClientName("");setClientPhone("");setNotice("");setSection("solicitacoes");}
 function changeAppointment(id:string,status:string){setData(current=>({...current,appointments:current.appointments.map(a=>a.id===id?{...a,status}:a)}));}
 function addService(){if(!newService.trim())return;const service:Service={id:uid(),name:newService.trim(),price:20000,duration:120,active:true,description:"",images:[],questionIds:[]};setData(d=>({...d,services:[...d.services,service]}));setNewService("");}
 function updateService(id:string,patch:Partial<Service>){setData(current=>({...current,services:current.services.map(s=>s.id===id?{...s,...patch}:s)}));}
 function addQuestion(){const q:CustomerQuestion={id:uid(),label:"Nova pergunta",kind:"text",required:false,options:[],serviceIds:[]};setData(d=>({...d,questions:[...d.questions,q]}));}
 function updateQuestion(id:string,patch:Partial<CustomerQuestion>){setData(current=>({...current,questions:current.questions.map(q=>q.id===id?{...q,...patch}:q),services:patch.serviceIds?current.services.map(s=>({...s,questionIds:patch.serviceIds!.includes(s.id)?Array.from(new Set([...s.questionIds,id])):s.questionIds.filter(qid=>qid!==id)})):current.services}));}
 function addBlock(){if(!blockDay||timeMinutes(blockEnd)<=timeMinutes(blockStart)){setNotice("Escolha um intervalo válido para o bloqueio.");return;}setData(d=>({...d,blocks:[...d.blocks,{id:uid(),day:blockDay,start:blockStart,end:blockEnd,label:"Indisponível"}]}));setNotice("Horário bloqueado na agenda.");}
 function updateHour(index:number,key:keyof Hour,value:string|boolean){setData(d=>({...d,hours:d.hours.map((h,i)=>i===index?{...h,[key]:value}:h)}));}
 function addPortfolioImage(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")||file.size>1_000_000){setNotice("Escolha uma imagem de até 1 MB para manter a demonstração dentro do armazenamento local.");return;}const reader=new FileReader();reader.onload=()=>{const service=data.services.find(s=>s.id===portfolioService);if(service)updateService(service.id,{images:[...service.images,reader.result as string]});setNotice("Imagem salva neste navegador.")};reader.readAsDataURL(file);event.target.value="";}
 const monthTitle=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(month);

 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/"><BrandLogo /></Link><div className="side-label" style={{marginTop:25}}>Demonstração · Ana Tranças</div>{nav.map(({id,label,icon:Icon})=><button key={id} className={`side-link ${section===id?"active":""}`} onClick={()=>setSection(id)}><Icon size={17}/>{label}</button>)}<div className="side-bottom"><Link className="side-link" href="/demo/fluxo"><CalendarDays size={16}/>Testar fluxo cliente ↔ profissional <ArrowRight size={14}/></Link><Link className="side-link" href="/exemplo-trancista"><MapPin size={16}/>Prévia pública <ArrowRight size={14}/></Link><Link className="side-link" href="/"><House size={16}/>Voltar ao site</Link></div></aside>
 <main className="app-main"><div className="trial-box" style={{margin:"14px 18px 0",background:"var(--blush)"}}><b>Modo demonstração</b> · Dados fictícios, salvos somente neste navegador. Nenhuma alteração é publicada ou enviada.{saved&&<span style={{float:"right"}}>Salvo <Check size={13}/></span>}</div><header className="app-top"><span style={{fontSize:13,color:"var(--muted)"}}>Seu espaço de atendimento</span><div className="avatar">AM</div></header><div className="app-content"><div className="dash-heading"><div><span className="eyebrow">Ana Tranças · Salvador</span><h1>{titles[section]}</h1><p>{section==="cliente"?"Escolha o dia no calendário e envie sua solicitação.":"Informações demonstrativas salvas localmente neste navegador."}</p></div>{section==="cliente"&&<button className="btn secondary" onClick={()=>{setBookingDay("");setSection("agenda")}}><ArrowLeft size={16}/> Voltar ao calendário</button>}</div>
 {section==="inicio"&&<><div className="stats"><article className="stat-card"><span className="stat-label">Atendimentos hoje</span><div className="stat-value">{appointmentsOn(offsetDate(0)).length}</div><span className="stat-note">{prettyDate(offsetDate(0),{day:"numeric",month:"short"})}</span></article><article className="stat-card"><span className="stat-label">Aguardando resposta</span><div className="stat-value">{data.appointments.filter(a=>a.status==="Nova solicitação").length}</div><span className="stat-note">Solicitações para revisar</span></article><article className="stat-card"><span className="stat-label">Este mês</span><div className="stat-value">{data.appointments.filter(a=>dateFromKey(a.day).getMonth()===month.getMonth()&&a.status==="Confirmado").length}</div><span className="stat-note">Atendimentos confirmados</span></article><article className="stat-card"><span className="stat-label">Receita prevista</span><div className="stat-value">{money(data.appointments.filter(a=>a.status==="Confirmado").reduce((sum,a)=>sum+a.price,0))}</div><span className="stat-note">Com base nos confirmados</span></article></div><div className="dash-grid"><Panel title="Próximos atendimentos">{data.appointments.slice().sort((a,b)=>a.day.localeCompare(b.day)||a.time.localeCompare(b.time)).slice(0,4).map(a=><AppointmentRow key={a.id} appointment={a} service={data.services.find(s=>s.id===a.serviceId)?.name??"Serviço"}/>)}</Panel><div><Panel title="Atalhos"><button className="quick-action" onClick={()=>setSection("agenda")}><CalendarDays size={16}/> Abrir calendário</button><button className="quick-action" onClick={()=>setSection("servicos")}><Scissors size={16}/> Editar serviços</button><button className="quick-action" onClick={()=>setSection("perguntas")}><Inbox size={16}/> Configurar perguntas</button></Panel></div></div></>}

 {section==="agenda"&&<><Panel title="Calendário mensal" aside={<MonthNav monthTitle={monthTitle} previous={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1,12))} next={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1,12))}/> }><div className="month-grid"><div className="month-weekdays">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(d=><span key={d}>{d}</span>)}</div><div className="month-days">{days.map(date=>{const key=dateKey(date),count=appointmentsOn(key).length,blocked=data.blocks.some(b=>b.day===key);return <button key={key} className={`month-day ${date.getMonth()!==month.getMonth()?"outside":""} ${key===selectedDay?"selected":""} ${key===offsetDate(0)?"today":""}`} onClick={()=>setSelectedDay(key)}><b>{date.getDate()}</b>{count>0&&<small>{count} atend.</small>}{blocked&&<i title="Há horário bloqueado"/>}</button>})}</div></div></Panel><Panel title={selectedDay?prettyDate(selectedDay):"Selecione um dia"} aside={selectedDay&&<button className="btn small" onClick={()=>openBooking(selectedDay)}><Plus size={14}/> Agendar atendimento</button>}>{selectedDay?appointmentsOn(selectedDay).length?appointmentsOn(selectedDay).map(a=><AppointmentRow key={a.id} appointment={a} service={data.services.find(s=>s.id===a.serviceId)?.name??"Serviço"}/>):<p>Nenhum atendimento neste dia. Horários livres são mostrados às clientes.</p>:<p>Clique em um dia do calendário para ver os atendimentos.</p>}</Panel><Panel title="Ver como cliente"><button className="btn" onClick={()=>{setBookingDay("");setSection("cliente")}}><CalendarDays size={16}/> Abrir calendário de agendamento</button></Panel></>}

 {section==="cliente"&&<section className="panel demo-booking"><div className="demo-public-head"><BrandLogo className="brand-logo brand-logo-compact"/><div><b>{data.displayName} · Trancista</b><small><MapPin size={12}/> {data.city}</small></div></div><p>{data.description}</p>{!bookingDay?<><h2 className="serif">Escolha um serviço e um dia</h2><div className="form-field"><label htmlFor="demo-service">Serviço</label><select id="demo-service" value={clientService} onChange={e=>{setClientService(e.target.value);setClientAnswers({})}}>{data.services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name} · {money(s.price)}</option>)}</select></div><MonthNav monthTitle={monthTitle} previous={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1,12))} next={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1,12))}/><div className="month-grid booking-month"><div className="month-weekdays">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(d=><span key={d}>{d}</span>)}</div><div className="month-days">{days.map(date=>{const key=dateKey(date),open=selectedService?slotsOn(key,selectedService).length>0:false;return <button key={key} disabled={!open||date<new Date(new Date().setHours(0,0,0,0))} className={`month-day ${date.getMonth()!==month.getMonth()?"outside":""} ${open?"available":""}`} onClick={()=>setBookingDay(key)}><b>{date.getDate()}</b>{open&&<small>Disponível</small>}</button>})}</div></div></>:<BookingDay day={bookingDay} service={selectedService} questions={customerQuestions} answers={clientAnswers} setAnswers={setClientAnswers} name={clientName} setName={setClientName} phone={clientPhone} setPhone={setClientPhone} slots={selectedService?slotsOn(bookingDay,selectedService,quote.duration):[]} price={quote.price} duration={quote.duration} onBack={()=>setBookingDay("")} onSubmit={submitBooking}/>} {notice&&<p className="form-error" role="alert">{notice}</p>}{clientSuccess&&<p className="trial-box" role="status">{clientSuccess}</p>}<p className="demo-disclaimer">Demonstração: nenhum dado sai deste navegador.</p></section>}

 {section==="solicitacoes"&&<Panel title="Pedidos recentes">{data.appointments.filter(a=>a.status==="Nova solicitação"||a.status==="Aguardando resposta").length?data.appointments.filter(a=>a.status==="Nova solicitação"||a.status==="Aguardando resposta").sort((a,b)=>a.day.localeCompare(b.day)||a.time.localeCompare(b.time)).map(a=><article className="request-card" key={a.id}><div className="request-head"><div><span className="status">ID {String(customers.findIndex(c=>c.phone.replace(/\D/g,"")===a.phone.replace(/\D/g,""))+1).padStart(4,"0")}</span><h3>{a.client}</h3></div><span className="status">{a.status}</span></div><p>☎️: {a.phone||"Contato não informado"}</p><p>📅: {prettyDate(a.day,{weekday:"long",day:"numeric",month:"long"})}</p><p>🕝: {a.time}</p><p>👩‍🦱: {data.services.find(s=>s.id===a.serviceId)?.name??"Serviço"}</p><details><summary>Ver detalhes do serviço</summary><div className="request-details"><p><b>Serviço:</b> {data.services.find(s=>s.id===a.serviceId)?.name??"Serviço"}</p><p><b>Preço estimado:</b> {money(a.price)} · <b>Duração:</b> {a.duration} min</p>{a.answers.map((answer,i)=><p key={i}><b>{answer.question}:</b> {answer.value||"Sem resposta"}</p>)}</div></details><div className="local-flow-actions"><button className="btn small" onClick={()=>changeAppointment(a.id,"Confirmado")}><Check size={13}/> Confirmar</button><button className="btn small secondary" onClick={()=>changeAppointment(a.id,"Recusado")}><X size={13}/> Recusar</button></div></article>):<p>Não há solicitações aguardando resposta.</p>}</Panel>}

 {section==="clientes"&&<Panel title="Clientes por telefone">{customers.length?customers.map((customer,index)=><details className="customer-card" key={customer.phone}><summary><span className="avatar">{customer.name.slice(0,1)}</span><span className="row-main"><b>{customer.name}</b><small>{customer.phone} · {customer.visits.length} atendimento(s)</small></span><span className="status">Cliente {String(index+1).padStart(4,"0")}</span></summary><div className="customer-history">{customer.visits.slice().sort((a,b)=>b.day.localeCompare(a.day)).map(a=><AppointmentRow key={a.id} appointment={a} service={data.services.find(s=>s.id===a.serviceId)?.name??"Serviço"}/>)}</div></details>):<p>Os clientes aparecem aqui após enviarem uma solicitação com contato.</p>}</Panel>}

 {section==="servicos"&&<><Panel title="Seus serviços"><div className="service-editor-list">{data.services.map(service=><details className="service-editor" key={service.id}><summary><span className="service-thumb">{service.images[0]?<img src={service.images[0]} alt=""/>:<Scissors size={20}/>}</span><span className="row-main"><b>{service.name||"Novo serviço"}</b><small>{money(service.price)} · {service.duration} min · {service.active?"Disponível":"Pausado"}</small></span><ArrowRight size={15}/></summary><div className="service-editor-body"><div className="form-field"><label>Nome do serviço</label><input required value={service.name} onChange={e=>updateService(service.id,{name:e.target.value})}/></div><div className="form-field"><label>Descrição</label><textarea value={service.description} onChange={e=>updateService(service.id,{description:e.target.value})}/></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr"}}><div className="form-field"><label>Valor (R$)</label><input type="number" min="0" step="0.01" value={(service.price/100).toFixed(2)} onChange={e=>updateService(service.id,{price:Math.round(Number(e.target.value)*100)||0})}/></div><div className="form-field"><label>Duração (minutos)</label><input type="number" min="1" value={service.duration} onChange={e=>updateService(service.id,{duration:Math.max(1,Number(e.target.value)||1)})}/></div></div><label className="inline-check"><input type="checkbox" checked={service.active} onChange={e=>updateService(service.id,{active:e.target.checked})}/> Disponível para agendamento</label><p>{service.images.length} imagem(ns) associada(s). Edite perguntas na área “Perguntas para clientes”.</p></div></details>)}</div></Panel><Panel title="Adicionar serviço"><div className="form-field"><label htmlFor="new-service">Nome do serviço</label><input id="new-service" value={newService} onChange={e=>setNewService(e.target.value)} placeholder="Ex.: Nail art"/></div><button className="btn" onClick={addService}><Plus size={15}/> Criar serviço</button></Panel></>}

 {section==="perguntas"&&<><Panel title="Perguntas do formulário"><p>Crie perguntas apropriadas para sua área e associe cada uma a um ou mais serviços.</p>{data.questions.map((q,index)=><article className="question-editor" key={q.id}><div className="panel-title"><b>Pergunta {index+1}</b><button className="btn small secondary" aria-label="Remover pergunta" onClick={()=>setData(d=>({...d,questions:d.questions.filter(x=>x.id!==q.id),services:d.services.map(s=>({...s,questionIds:s.questionIds.filter(id=>id!==q.id)}))}))}><Trash2 size={13}/></button></div><div className="form-field"><label>Pergunta</label><input value={q.label} onChange={e=>updateQuestion(q.id,{label:e.target.value})}/></div><div className="form-field"><label>Tipo de resposta</label><select value={q.kind} onChange={e=>updateQuestion(q.id,{kind:e.target.value as CustomerQuestion["kind"],options:e.target.value==="single"||e.target.value==="multiple"?q.options:[]})}><option value="text">Texto</option><option value="single">Escolha única</option><option value="multiple">Múltipla escolha</option><option value="yesno">Sim ou não</option></select></div><label className="inline-check"><input type="checkbox" checked={q.required} onChange={e=>updateQuestion(q.id,{required:e.target.checked})}/> Obrigatória</label>{(q.kind==="single"||q.kind==="multiple")&&<div className="question-options">{q.options.map((o,oi)=><div className="option-row" key={o.id}><input aria-label={`Opção ${oi+1}`} value={o.label} onChange={e=>updateQuestion(q.id,{options:q.options.map(x=>x.id===o.id?{...x,label:e.target.value}:x)})} placeholder="Opção"/><input aria-label="Valor adicional em reais" type="number" step="0.01" value={(o.price/100).toFixed(2)} onChange={e=>updateQuestion(q.id,{options:q.options.map(x=>x.id===o.id?{...x,price:Math.round(Number(e.target.value)*100)||0}:x)})}/><input aria-label="Minutos adicionais" type="number" value={o.minutes} onChange={e=>updateQuestion(q.id,{options:q.options.map(x=>x.id===o.id?{...x,minutes:Number(e.target.value)||0}:x)})}/><button className="pill" aria-label="Excluir opção" onClick={()=>updateQuestion(q.id,{options:q.options.filter(x=>x.id!==o.id)})}><X size={12}/></button></div>)}<button className="btn secondary small" onClick={()=>updateQuestion(q.id,{options:[...q.options,{id:uid(),label:"",price:0,minutes:0}]})}><Plus size={13}/> Adicionar opção</button></div>}<div className="form-field"><label>Serviços relacionados</label><div className="check-grid">{data.services.map(s=><label key={s.id}><input type="checkbox" checked={q.serviceIds.includes(s.id)} onChange={e=>updateQuestion(q.id,{serviceIds:e.target.checked?[...q.serviceIds,s.id]:q.serviceIds.filter(id=>id!==s.id)})}/>{s.name}</label>)}</div></div></article>)}<button className="btn" onClick={addQuestion}><Plus size={15}/> Nova pergunta</button></Panel></>}

 {section==="financeiro"&&<><div className="stats"><article className="stat-card"><span className="stat-label">Previsto</span><div className="stat-value">{money(data.appointments.filter(a=>a.status==="Confirmado"||a.status==="Nova solicitação").reduce((sum,a)=>sum+a.price,0))}</div></article><article className="stat-card"><span className="stat-label">Confirmado</span><div className="stat-value">{money(data.appointments.filter(a=>a.status==="Confirmado").reduce((sum,a)=>sum+a.price,0))}</div></article><article className="stat-card"><span className="stat-label">Solicitações</span><div className="stat-value">{money(data.appointments.filter(a=>a.status==="Nova solicitação").reduce((sum,a)=>sum+a.price,0))}</div></article></div><Panel title="Valores da agenda">{data.appointments.filter(a=>a.status!=="Recusado"&&a.status!=="Cancelado").sort((a,b)=>a.day.localeCompare(b.day)).map(a=><AppointmentRow key={a.id} appointment={a} service={data.services.find(s=>s.id===a.serviceId)?.name??"Serviço"} detail={money(a.price)}/>)}</Panel></>}

 {section==="portfolio"&&<><Panel title="Fotos dos serviços"><p>Escolha o serviço para associar imagens. Cada arquivo de até 1 MB fica neste navegador.</p><div className="form-field"><label htmlFor="portfolio-service">Serviço</label><select id="portfolio-service" value={portfolioService} onChange={e=>setPortfolioService(e.target.value)}>{data.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="portfolio-grid">{data.services.flatMap(s=>s.images.map((image,index)=><article className="portfolio-item panel" key={`${s.id}-${index}`}><img src={image} alt={`Portfólio: ${s.name}`}/><b>{s.name}</b><button className="btn small secondary" onClick={()=>updateService(s.id,{images:s.images.filter((_,i)=>i!==index)})}><Trash2 size={13}/> Remover foto</button></article>))}</div><label className="btn secondary" style={{marginTop:14,display:"inline-flex"}}><Plus size={15}/> Adicionar imagem<input type="file" accept="image/*" onChange={addPortfolioImage} hidden/></label>{notice&&<p role="status">{notice}</p>}</Panel></>}

 {section==="minha-pagina"&&<section className="panel" style={{maxWidth:650,margin:"0 auto",padding:28}}><div className="profile-hero"/><div className="profile-info"><span className="profile-avatar">{data.displayName.slice(0,2).toUpperCase()}</span><span className="eyebrow">Beleza · {data.city}</span><h2 className="serif" style={{fontSize:34,margin:"8px 0"}}>{data.displayName}</h2><p>{data.description}</p><div className="service-list">{data.services.filter(s=>s.active).map(s=><article className="service-card" key={s.id}><span className="service-thumb">{s.images[0]?<img src={s.images[0]} alt=""/>:<Scissors size={20}/>}</span><div className="service-text"><b>{s.name}</b><small><Clock3 size={12}/> {s.duration} min</small></div><div className="service-price">A partir de {money(s.price)}</div></article>)}</div><p className="pill">tamarcado.com.br/{data.slug} · Prévia fictícia</p></div></section>}

 {section==="configuracoes"&&<div className="panel" style={{maxWidth:800}}><span className="eyebrow">Seu negócio, seu jeito</span><h2 className="serif" style={{fontSize:26}}>Informações do espaço</h2><div className="form-field"><label htmlFor="displayName">Nome profissional</label><input id="displayName" value={data.displayName} onChange={e=>setData(d=>({...d,displayName:e.target.value}))}/></div><div className="form-field"><label htmlFor="business">Nome do negócio</label><input id="business" value={data.business} onChange={e=>setData(d=>({...d,business:e.target.value}))}/></div><div className="form-field"><label htmlFor="whatsapp">WhatsApp profissional</label><input id="whatsapp" value={data.whatsapp} onChange={e=>setData(d=>({...d,whatsapp:e.target.value}))}/></div><div className="form-field"><label htmlFor="city">Localização pública</label><input id="city" value={data.city} onChange={e=>setData(d=>({...d,city:e.target.value}))}/></div><div className="form-field"><label htmlFor="slug">Link da página</label><input id="slug" value={data.slug} onChange={e=>setData(d=>({...d,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")}))}/></div><div className="form-field"><label htmlFor="description">Sobre seu trabalho</label><textarea id="description" rows={4} value={data.description} onChange={e=>setData(d=>({...d,description:e.target.value}))}/></div><h3>Horários de atendimento</h3><p>Defina o início e o fim do expediente, além da pausa para almoço.</p>{data.hours.map((hour,index)=><div className="hours-row" key={hour.day}><label><input type="checkbox" checked={hour.enabled} onChange={e=>updateHour(index,"enabled",e.target.checked)}/>{hour.day}</label><input aria-label={`${hour.day}: início`} type="time" value={hour.start} onChange={e=>updateHour(index,"start",e.target.value)} disabled={!hour.enabled}/><input aria-label={`${hour.day}: almoço início`} type="time" value={hour.lunchStart} onChange={e=>updateHour(index,"lunchStart",e.target.value)} disabled={!hour.enabled}/><input aria-label={`${hour.day}: almoço fim`} type="time" value={hour.lunchEnd} onChange={e=>updateHour(index,"lunchEnd",e.target.value)} disabled={!hour.enabled}/><input aria-label={`${hour.day}: fim`} type="time" value={hour.end} onChange={e=>updateHour(index,"end",e.target.value)} disabled={!hour.enabled}/></div>)}<div className="hours-legend"><span>Dia</span><span>Início</span><span>Almoço ida</span><span>Almoço volta</span><span>Fim</span></div><p className="demo-disclaimer">Edição demonstrativa: as alterações são guardadas localmente.</p></div>}

 {section==="bloqueios"&&<><Panel title="Novo bloqueio"><p>Defina um dia e o intervalo em que não quer receber agendamentos.</p><div className="form-field"><label htmlFor="block-day">Dia</label><input id="block-day" type="date" value={blockDay} onChange={e=>setBlockDay(e.target.value)}/></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr"}}><div className="form-field"><label htmlFor="block-start">Início</label><input id="block-start" type="time" value={blockStart} onChange={e=>setBlockStart(e.target.value)}/></div><div className="form-field"><label htmlFor="block-end">Fim</label><input id="block-end" type="time" value={blockEnd} onChange={e=>setBlockEnd(e.target.value)}/></div></div><button className="btn" onClick={addBlock}><Plus size={15}/> Bloquear horário</button>{notice&&<p role="status">{notice}</p>}</Panel><Panel title="Bloqueios cadastrados">{data.blocks.length?data.blocks.slice().sort((a,b)=>a.day.localeCompare(b.day)).map(block=><div className="appointment-row" key={block.id}><b>{prettyDate(block.day)}</b><span className="row-main">{block.start}–{block.end}</span><button className="btn small secondary" aria-label="Remover bloqueio" onClick={()=>setData(d=>({...d,blocks:d.blocks.filter(b=>b.id!==block.id)}))}><Trash2 size={13}/></button></div>):<p>Nenhum bloqueio cadastrado.</p>}</Panel></>}

 {section==="assinatura"&&<Panel title="Plano único"><span className="pill">10 atendimentos gratuitos</span><div className="price-big">R$ 29,90 <small>/ mês</small></div><p>Prévia demonstrativa. Nenhuma cobrança será iniciada.</p></Panel>}
 </div><footer style={{padding:"0 30px 24px",color:"var(--muted)",fontSize:11}}>Demonstração · Informações fictícias ficam neste navegador.</footer></main><nav className="mobile-nav">{nav.map(({id,label,icon:Icon})=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon size={18}/>{label}</button>)}</nav></div>;
}

function MonthNav({monthTitle,previous,next}:{monthTitle:string;previous:()=>void;next:()=>void}){return <div className="month-nav"><button className="pill" aria-label="Mês anterior" onClick={previous}><ChevronLeft size={16}/></button><b>{monthTitle}</b><button className="pill" aria-label="Próximo mês" onClick={next}><ChevronRight size={16}/></button></div>}
function AppointmentRow({appointment:a,service,detail}:{appointment:DemoAppointment;service:string;detail?:string}){return <article className="appointment-row"><span className="time-col">{a.time}</span><span className="avatar">{a.client.slice(0,1)}</span><div className="row-main"><b>{a.client}</b><small>{prettyDate(a.day,{weekday:"short",day:"numeric",month:"short"})} · {service} · {a.status}</small></div><span className="status">{detail??a.status}</span></article>}
function BookingDay({day,service,questions,answers,setAnswers,name,setName,phone,setPhone,slots,price,duration,onBack,onSubmit}:{day:string;service?:Service;questions:CustomerQuestion[];answers:Record<string,string>;setAnswers:(v:Record<string,string>)=>void;name:string;setName:(v:string)=>void;phone:string;setPhone:(v:string)=>void;slots:string[];price:number;duration:number;onBack:()=>void;onSubmit:()=>void}){const digits=phone.replace(/\D/g,"");return <section className="booking-day"><button className="text-button" onClick={onBack}><ArrowLeft size={14}/> Trocar dia</button><h2 className="serif">{prettyDate(day)}</h2><p>{service?.name} · {money(price)} · {duration} min</p><div className="form-field"><label>Horários disponíveis</label><div className="demo-slots">{slots.length?slots.map(slot=><button key={slot} className={`pill ${answers.__time===slot?"selected":""}`} onClick={()=>setAnswers({...answers,__time:slot})}>{slot}</button>):<span>Sem horários livres para esse serviço e essas respostas.</span>}</div></div>{questions.map(q=><div className="form-field" key={q.id}><label>{q.label}{q.required?" *":" (opcional)"}</label>{q.kind==="single"||q.kind==="multiple"?<div className="demo-slots">{q.options.map(o=><button key={o.id} className={`pill ${(answers[q.id]??"").split(", ").includes(o.label)?"selected":""}`} onClick={()=>setAnswers({...answers,[q.id]:q.kind==="single"?o.label:(answers[q.id]??"").split(", ").includes(o.label)?(answers[q.id]??"").split(", ").filter(x=>x!==o.label).join(", "):[...(answers[q.id]??"").split(", ").filter(Boolean),o.label].join(", ")})}>{o.label}{o.price?` · +${money(o.price)}`:""}{o.minutes?` · +${o.minutes} min`:""}</button>)}</div>:q.kind==="yesno"?<select value={answers[q.id]??""} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}><option value="">Escolha</option><option>Sim</option><option>Não</option></select>:<input value={answers[q.id]??""} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/>}</div>)}<div className="form-field"><label htmlFor="client-full-name">Nome completo *</label><input id="client-full-name" required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Bruna Souza"/></div><div className="form-field"><label htmlFor="client-phone">Contato com DDD *</label><input id="client-phone" required type="tel" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(11) 91234-5678"/><small>Informe um telefone com DDD (10 ou 11 números).</small>{phone&&digits.length<10&&<span className="form-error">Digite DDD e número de contato.</span>}</div><button className="btn" disabled={!answers.__time||!name.trim()||digits.length<10} onClick={onSubmit}><Check size={15}/> Enviar solicitação</button></section>}
