"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, CircleDollarSign, Clock3, CreditCard, House, Image, Inbox, MapPin, Plus, Scissors, Settings, Users, X } from "lucide-react";

type Section="inicio"|"agenda"|"cliente"|"solicitacoes"|"clientes"|"servicos"|"financeiro"|"portfolio"|"minha-pagina"|"configuracoes"|"assinatura";
type DemoAppointment={id:string;dayOffset:number;time:string;client:string;service:string;status:string};
type DemoData={displayName:string;business:string;whatsapp:string;city:string;slug:string;description:string;services:{name:string;price:number;duration:number;active:boolean;questions?:unknown[]}[];hours:{day:string;enabled:boolean;start:string;end:string}[];appointments:DemoAppointment[]};
const initial:DemoData={displayName:"Ana Martins",business:"Ana Tranças",whatsapp:"(71) 99999-1234",city:"Rio Vermelho, Salvador",slug:"ana-trancas",description:"Tranças feitas com carinho e atenção a cada detalhe. Vamos encontrar o estilo ideal para você?",services:[{name:"Box braids",price:22000,duration:240,active:true},{name:"Nagô",price:10000,duration:120,active:true},{name:"Twist",price:18000,duration:180,active:true}],hours:["Segunda","Terça","Quarta","Quinta","Sexta","Sábado"].map((day,index)=>({day,enabled:index<5,start:"09:00",end:"18:00"})),appointments:[{id:"demo-1",dayOffset:0,time:"14:00",client:"Camila Santos",service:"Box braids",status:"Confirmado"},{id:"demo-2",dayOffset:1,time:"09:30",client:"Júlia Oliveira",service:"Nagô",status:"Confirmado"},{id:"demo-3",dayOffset:3,time:"11:00",client:"Mariana Costa",service:"Twist",status:"Aguardando resposta"}]};
const nav:{id:Section;label:string;icon:typeof House}[]=[{id:"inicio",label:"Início",icon:House},{id:"agenda",label:"Agenda",icon:CalendarDays},{id:"solicitacoes",label:"Solicitações",icon:Inbox},{id:"clientes",label:"Clientes",icon:Users},{id:"servicos",label:"Serviços",icon:Scissors},{id:"financeiro",label:"Financeiro",icon:CircleDollarSign},{id:"portfolio",label:"Portfólio",icon:Image},{id:"minha-pagina",label:"Minha página",icon:MapPin},{id:"configuracoes",label:"Configurações",icon:Settings},{id:"assinatura",label:"Assinatura",icon:CreditCard}];
function localDate(offset:number){const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()+offset);return date;}
function dateLabel(offset:number,options:Intl.DateTimeFormatOptions={weekday:"short",day:"numeric",month:"short"}){return new Intl.DateTimeFormat("pt-BR",options).format(localDate(offset));}
function getSlots(data:DemoData,dayOffset:number,service:{duration:number}){const date=localDate(dayOffset),dayIndex=(date.getDay()+6)%7,rule=data.hours[dayIndex];if(!rule?.enabled)return[];const [sh,sm]=rule.start.split(":").map(Number),[eh,em]=rule.end.split(":").map(Number),start=sh*60+sm,end=eh*60+em,occupied=data.appointments.filter(a=>a.dayOffset===dayOffset&&a.status==="Confirmado").map(a=>{const [h,m]=a.time.split(":").map(Number),s=h*60+m,d=data.services.find(x=>x.name===a.service)?.duration??120;return[s,s+d]});const result:string[]=[];for(let minute=start;minute+service.duration<=end;minute+=30){if(occupied.some(([a,b])=>minute<b&&minute+service.duration>a))continue;result.push(`${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`)}return result;}
export function DemoWorkspace(){
 const [section,setSection]=useState<Section>("inicio"),[data,setData]=useState(initial),[ready,setReady]=useState(false),[saved,setSaved]=useState(false),[newService,setNewService]=useState(""),[selectedDay,setSelectedDay]=useState(0),[clientDay,setClientDay]=useState(1),[clientService,setClientService]=useState(initial.services[0].name),[clientSlot,setClientSlot]=useState(""),[clientName,setClientName]=useState(""),[clientSuccess,setClientSuccess]=useState("");
 useEffect(()=>{const read=()=>{try{const stored=localStorage.getItem("ta-marcado-demo-v1");if(stored){const value=JSON.parse(stored);setData({...initial,...value,services:(value.services??initial.services).map((s:{name:string;price:number})=>({...s,price:s.price<10000?s.price*100:s.price})),hours:value.hours??initial.hours,appointments:value.appointments??initial.appointments})}}catch{}};read();setReady(true);const sync=(event:StorageEvent)=>{if(event.key==="ta-marcado-demo-v1")read()};window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync)},[]);
 useEffect(()=>{if(ready){localStorage.setItem("ta-marcado-demo-v1",JSON.stringify(data));setSaved(true);const timer=setTimeout(()=>setSaved(false),1500);return()=>clearTimeout(timer)}},[data,ready]);
 const update=(key:keyof DemoData,value:string)=>setData(current=>({...current,[key]:value}));
 const updateHour=(index:number,key:"enabled"|"start"|"end",value:boolean|string)=>setData(current=>({...current,hours:current.hours.map((hour,i)=>i===index?{...hour,[key]:value}:hour)}));
 const titles:Record<Section,string>={inicio:"Bom dia, Ana ☀️",agenda:"Agenda",cliente:"Agendar como cliente",solicitacoes:"Solicitações",clientes:"Clientes",servicos:"Seus serviços",financeiro:"Financeiro",portfolio:"Portfólio", "minha-pagina":"Sua página pública",configuracoes:"Configurações do espaço",assinatura:"Seu plano"};
 const activeService=data.services.find(service=>service.name===clientService)??data.services[0];
 const clientSlots=activeService?getSlots(data,clientDay,activeService):[];
 const upcoming=data.appointments.slice().sort((a,b)=>a.dayOffset-b.dayOffset||a.time.localeCompare(b.time)).map(a=>({time:`${dateLabel(a.dayOffset)} · ${a.time}`,client:a.client,service:a.service,status:a.status}));
 function requestDemoBooking(){if(!activeService||!clientName.trim()||!clientSlot)return;const request:DemoAppointment={id:`demo-${Date.now()}`,dayOffset:clientDay,time:clientSlot,client:clientName.trim(),service:activeService.name,status:"Nova solicitação"};setData(current=>({...current,appointments:[...current.appointments,request]}));setSelectedDay(clientDay);setClientSuccess(`Solicitação enviada para ${dateLabel(clientDay,{weekday:"long",day:"numeric",month:"long"})} às ${clientSlot}. Ela já apareceu na agenda da profissional.`);setClientSlot("");setSection("agenda");}
 function changeAppointment(id:string,status:string){setData(current=>({...current,appointments:current.appointments.map(a=>a.id===id?{...a,status}:a)}));}
 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark">t</span><span>tá marcado</span></Link><div className="side-label" style={{marginTop:25}}>Demonstração · Ana Tranças</div>{nav.map(({id,label,icon:Icon})=><button key={id} className={`side-link ${section===id?"active":""}`} onClick={()=>setSection(id)}><Icon size={17}/>{label}</button>)}<div className="side-bottom"><Link className="side-link" href="/demo/fluxo"><CalendarDays size={16}/>Testar fluxo cliente ↔ profissional <ArrowRight size={14}/></Link><Link className="side-link" href="/exemplo-trancista"><MapPin size={16}/>Prévia pública <ArrowRight size={14}/></Link><Link className="side-link" href="/"><House size={16}/>Voltar ao site</Link></div></aside>
 <main className="app-main"><div className="trial-box" style={{margin:"14px 18px 0",background:"#f4eee0"}}><b>Modo demonstração</b> · Dados fictícios, salvos somente neste navegador. Nenhuma alteração é publicada ou enviada.{saved&&<span style={{float:"right"}}>Salvo <Check size={13}/></span>}</div><header className="app-top"><span style={{fontSize:13,color:"var(--muted)"}}>Seu espaço de atendimento</span><div className="avatar">AM</div></header><div className="app-content"><div className="dash-heading"><div><span className="eyebrow">Ana Tranças · Salvador</span><h1>{titles[section]}</h1><p>{section==="inicio"?"Veja o que acontece no seu espaço hoje.":section==="cliente"?"Confira os horários livres e envie uma solicitação.":"Explore como essa área pode funcionar no seu dia a dia."}</p></div>{section==="agenda"&&<button className="btn" onClick={()=>setSection("cliente")}><CalendarDays size={16}/> Ver agenda como cliente</button>}{section==="cliente"&&<button className="btn secondary" onClick={()=>setSection("agenda")}><ArrowRight size={16}/> Voltar à agenda profissional</button>}</div>
 {section==="inicio"&&<><div className="stats"><article className="stat-card"><span className="stat-label">Atendimentos hoje</span><div className="stat-value">1</div><span className="stat-note">Próximo às 14:00</span></article><article className="stat-card"><span className="stat-label">Aguardando resposta</span><div className="stat-value">1</div><span className="stat-note">Solicitações para revisar</span></article><article className="stat-card"><span className="stat-label">Esta semana</span><div className="stat-value">8</div><span className="stat-note">Atendimentos na agenda</span></article><article className="stat-card"><span className="stat-label">Receita prevista</span><div className="stat-value">R$ 1.240</div><span className="stat-note">Esta semana</span></article></div><div className="dash-grid"><Panel title="Próximos atendimentos">{upcoming.slice(0,2).map(row=><Row key={row.client} title={row.client} detail={`${row.time} · ${row.service}`} status={row.status}/>)}</Panel><div><Panel title="Atendimentos grátis"><div className="trial-top"><span>Progresso do teste</span><span>6 de 10</span></div><div className="progress"><span style={{width:"60%"}}/></div><p>Mais 4 atendimentos concluídos antes de escolher o plano.</p></Panel><Panel title="Atalhos"><button className="quick-action" onClick={()=>setSection("servicos")}><Scissors size={16}/> Ver meus serviços</button><button className="quick-action" onClick={()=>setSection("configuracoes")}><Settings size={16}/> Configurar meu espaço</button></Panel></div></div></>}
 {section==="agenda"&&<><Panel title="Semana · selecione um dia"><div className="demo-week">{Array.from({length:7},(_,offset)=><button key={offset} className={`demo-day ${selectedDay===offset?"selected":""}`} onClick={()=>setSelectedDay(offset)}><span>{dateLabel(offset,{weekday:"short"})}</span><b>{dateLabel(offset,{day:"numeric"})}</b><small>{data.appointments.filter(a=>a.dayOffset===offset&&a.status!=="Cancelado"&&a.status!=="Recusado").length} atend.</small></button>)}</div></Panel><Panel title={dateLabel(selectedDay,{weekday:"long",day:"numeric",month:"long"})}><div className="demo-timeline">{Array.from({length:10},(_,i)=>9+i).map(hour=><div className="demo-hour" key={hour}><span>{String(hour).padStart(2,"0")}:00</span><div>{data.appointments.filter(a=>a.dayOffset===selectedDay&&Number(a.time.slice(0,2))===hour&&a.status!=="Cancelado"&&a.status!=="Recusado").map(a=><article className={`demo-event ${a.status==="Confirmado"?"confirmed":"pending"}`} key={a.id}><b>{a.time} · {a.client}</b><span>{a.service}</span><small>{a.status}</small></article>)}</div></div>)}</div>{!data.appointments.some(a=>a.dayOffset===selectedDay&&a.status!=="Cancelado"&&a.status!=="Recusado")&&<p>Sem atendimentos neste dia. Seus horários livres aparecem para as clientes.</p>}</Panel><Panel title="Visão rápida da cliente"><p>Teste a outra ponta do agendamento. Ao enviar um pedido, ele entra nesta agenda e em Solicitações imediatamente.</p><button className="btn" onClick={()=>setSection("cliente")}><CalendarDays size={16}/> Abrir calendário público</button></Panel>{clientSuccess&&<p className="trial-box" role="status">{clientSuccess}</p>}</>}
 {section==="cliente"&&<section className="panel demo-booking"><div className="demo-public-head"><span className="brand-mark">t</span><div><b>{data.displayName} · Trancista</b><small><MapPin size={12}/> {data.city}</small></div></div><p>{data.description}</p><h2 className="serif">Vamos encontrar um horário?</h2><div className="form-field"><label htmlFor="demo-service">Escolha o serviço</label><select id="demo-service" value={clientService} onChange={e=>{setClientService(e.target.value);setClientSlot("")}}>{data.services.filter(s=>s.active).map(s=><option key={s.name} value={s.name}>{s.name} · R$ {s.price.toFixed(2).replace(".",",")} · {Math.floor(s.duration/60)}h</option>)}</select></div><div className="form-field"><label htmlFor="demo-day">Dia disponível</label><select id="demo-day" value={clientDay} onChange={e=>{setClientDay(Number(e.target.value));setClientSlot("")}}>{Array.from({length:14},(_,i)=>i).map(offset=><option key={offset} value={offset}>{dateLabel(offset,{weekday:"long",day:"numeric",month:"long"})}</option>)}</select></div><div className="form-field"><label>Horários livres</label><div className="demo-slots">{clientSlots.length?clientSlots.map(slot=><button type="button" key={slot} className={`pill ${clientSlot===slot?"selected":""}`} onClick={()=>setClientSlot(slot)}>{slot}</button>):<span style={{fontSize:13,color:"var(--muted)"}}>Não há horários para este dia/serviço. Escolha outra data.</span>}</div></div><div className="form-field"><label htmlFor="demo-client-name">Seu nome</label><input id="demo-client-name" value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Ex.: Bruna Souza"/></div><button className="btn" disabled={!clientSlot||!clientName.trim()} onClick={requestDemoBooking}><Check size={16}/> Solicitar este horário</button><p className="demo-disclaimer">Demonstração: nenhum dado sai deste navegador. A solicitação aparecerá na agenda da Ana nesta mesma tela.</p></section>}
 {section==="solicitacoes"&&<Panel title="Pedidos recentes">{data.appointments.filter(a=>a.status==="Nova solicitação"||a.status==="Aguardando resposta").length?data.appointments.filter(a=>a.status==="Nova solicitação"||a.status==="Aguardando resposta").map(a=><article className="appointment-row" key={a.id}><span className="avatar">{a.client.slice(0,1)}</span><div className="row-main"><b>{a.client}</b><small>{dateLabel(a.dayOffset,{weekday:"long",day:"numeric",month:"long"})} · {a.time} · {a.service}</small></div><span className="status">{a.status}</span><span style={{display:"flex",gap:6}}><button className="btn small" aria-label="Confirmar solicitação" onClick={()=>changeAppointment(a.id,"Confirmado")}><Check size={13}/></button><button className="btn small secondary" aria-label="Recusar solicitação" onClick={()=>changeAppointment(a.id,"Recusado")}><X size={13}/></button></span></article>):<p>Não há solicitações aguardando resposta.</p>}</Panel>}
 {section==="clientes"&&<Panel title="Clientes"><Row title="Camila Santos" detail="8 atendimentos · Último: 12 set" status="Frequente"/><Row title="Júlia Oliveira" detail="3 atendimentos · Próximo: amanhã" status="Agendado"/><Row title="Mariana Costa" detail="1 atendimento · Cliente nova" status="Nova"/></Panel>}
 {section==="servicos"&&<><Panel title="Catálogo de Ana">{data.services.map((service,index)=><Row key={`${service.name}-${index}`} title={service.name} detail={`${service.duration/60}h · ${service.active?"Ativo":"Pausado"}`} status={`R$ ${(service.price/100).toFixed(2).replace(".",",")}`}/>)}</Panel><Panel title="Adicionar serviço para experimentar"><div className="form-field"><label htmlFor="new-service">Nome do serviço</label><input id="new-service" value={newService} onChange={e=>setNewService(e.target.value)} placeholder="Ex.: Knotless braids"/></div><button className="btn" onClick={()=>{if(!newService.trim())return;setData(d=>({...d,services:[...d.services,{name:newService.trim(),price:20000,duration:240,active:true,questions:[]}]}));setNewService("")}}><Plus size={15}/> Adicionar à demonstração</button><p>Configure perguntas, opções e ajustes de preço e duração no laboratório local.</p></Panel></>}
 {section==="financeiro"&&<div className="stats"><article className="stat-card"><span className="stat-label">Previsto este mês</span><div className="stat-value">R$ 4.820</div></article><article className="stat-card"><span className="stat-label">Recebido</span><div className="stat-value">R$ 3.150</div></article><article className="stat-card"><span className="stat-label">Em aberto</span><div className="stat-value">R$ 1.670</div></article></div>}
 {section==="portfolio"&&<Panel title="Trabalhos de Ana"><div className="service-chips"><span className="pill">Box braids · 12 fotos</span><span className="pill">Nagô · 8 fotos</span><span className="pill">Twist · 5 fotos</span></div><p>As fotos do portfólio aparecem na página pública. Esta demonstração não envia arquivos.</p><button className="btn secondary" onClick={()=>alert("O envio de fotos requer a configuração do Supabase Storage.")}><Plus size={15}/> Adicionar foto (simulação)</button></Panel>}
 {section==="minha-pagina"&&<section className="panel" style={{maxWidth:650,margin:"0 auto",padding:28}}><div className="profile-hero"/><div className="profile-info"><span className="profile-avatar">{data.displayName.slice(0,2).toUpperCase()}</span><span className="eyebrow">Tranças · {data.city}</span><h2 className="serif" style={{fontSize:34,margin:"8px 0"}}>{data.displayName}</h2><p>{data.description}</p><div className="service-list">{data.services.filter(s=>s.active).map(s=><article className="service-card" key={s.name}><span className="service-thumb"><Scissors size={20}/></span><div className="service-text"><b>{s.name}</b><small><Clock3 size={12}/> {s.duration/60}h</small></div><div className="service-price">A partir de R$ {(s.price/100).toFixed(2).replace(".",",")}</div></article>)}</div><p className="pill">tamarcado.com.br/{data.slug} · Prévia fictícia</p></div></section>}
 {section==="configuracoes"&&<div className="panel" style={{maxWidth:720}}><span className="eyebrow">Seu negócio, seu jeito</span><h2 className="serif" style={{fontSize:26}}>Informações do espaço</h2><div className="form-field"><label htmlFor="displayName">Nome profissional</label><input id="displayName" value={data.displayName} onChange={e=>update("displayName",e.target.value)}/></div><div className="form-field"><label htmlFor="business">Nome do negócio</label><input id="business" value={data.business} onChange={e=>update("business",e.target.value)}/></div><div className="form-field"><label htmlFor="whatsapp">WhatsApp</label><input id="whatsapp" value={data.whatsapp} onChange={e=>update("whatsapp",e.target.value)}/></div><div className="form-field"><label htmlFor="city">Localização pública</label><input id="city" value={data.city} onChange={e=>update("city",e.target.value)}/><small>Mostramos apenas bairro e cidade, nunca seu endereço residencial.</small></div><div className="form-field"><label htmlFor="slug">Link da sua página</label><div style={{display:"flex",gap:8,alignItems:"center"}}><span>tamarcado.com.br/</span><input id="slug" value={data.slug} onChange={e=>update("slug",e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-"))}/></div></div><div className="form-field"><label htmlFor="description">Sobre seu trabalho</label><textarea id="description" rows={4} value={data.description} onChange={e=>update("description",e.target.value)}/></div><h3>Horários de atendimento</h3>{data.hours.map((hour,index)=><div className="appointment-row" key={hour.day}><b style={{width:90}}>{hour.day}</b><input type="checkbox" aria-label={`Atende ${hour.day}`} checked={hour.enabled} onChange={e=>updateHour(index,"enabled",e.target.checked)}/><input aria-label={`Início ${hour.day}`} type="time" value={hour.start} onChange={e=>updateHour(index,"start",e.target.value)} disabled={!hour.enabled}/><span>até</span><input aria-label={`Fim ${hour.day}`} type="time" value={hour.end} onChange={e=>updateHour(index,"end",e.target.value)} disabled={!hour.enabled}/></div>)}<p style={{fontSize:12,color:"var(--muted)"}}>Edição demonstrativa: as alterações são guardadas localmente neste navegador.</p></div>}
 {section==="assinatura"&&<Panel title="Plano único"><span className="pill">10 atendimentos gratuitos</span><div className="price-big">R$ 29,90 <small>/ mês</small></div><p>Sem comissão sobre seus atendimentos. Você mantém acesso aos seus dados e agenda.</p><button className="btn secondary" onClick={()=>alert("A assinatura real será ativada após conectar a conta Asaas.")}>Prévia do checkout (indisponível na demo)</button></Panel>}
 </div><footer style={{padding:"0 30px 24px",color:"var(--muted)",fontSize:11}}>Demonstração de interface · As informações são fictícias e ficam neste navegador.</footer></main><nav className="mobile-nav">{nav.slice(0,5).map(({id,label,icon:Icon})=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon size={18}/>{label}</button>)}</nav></div>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel" style={{marginBottom:16}}><div className="panel-title">{title}</div>{children}</section>}
function Row({title,detail,status,actions}:{title:string;detail:string;status:string;actions?:boolean}){return <article className="appointment-row"><span className="avatar">{title.slice(0,1)}</span><div className="row-main"><b>{title}</b><small>{detail}</small></div><span className="status">{status}</span>{actions&&<span style={{display:"flex",gap:6}}><button className="btn small" aria-label="Aceitar"><Check size={13}/></button><button className="btn small secondary" aria-label="Recusar"><X size={13}/></button></span>}</article>}
