"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, Plus, Send, Settings2, UserRound } from "lucide-react";

const KEY="ta-marcado-demo-v1";
type Kind="single"|"multiple"|"text"|"number"|"yesno"|"photo";
type Option={id:string;label:string;price:number;minutes:number};
type Question={id:string;label:string;kind:Kind;required:boolean;options:Option[]};
type Service={name:string;price:number;duration:number;active:boolean;questions:Question[]};
type Answer={questionId:string;label:string;value:string;optionIds:string[]};
type Proposal={dayOffset:number;time:string;price:number;duration:number;note?:string};
type Appointment={id:string;dayOffset:number;time:string;client:string;phone?:string;service:string;status:string;price:number;duration:number;answers:Answer[];proposal?:Proposal;history:string[]};
type Hour={day:string;enabled:boolean;start:string;end:string};
type State={displayName:string;business:string;city:string;slug:string;description:string;services:Service[];hours:Hour[];appointments:Appointment[]};
const question=(label:string,kind:Kind,options:Option[]=[]):Question=>({id:crypto.randomUUID(),label,kind,required:true,options});
const templates:Record<string,Question[]>={"Box braids":[{id:"q-length",label:"Qual comprimento você prefere?",kind:"single",required:true,options:[{id:"l-short",label:"Curta",price:0,minutes:0},{id:"l-medium",label:"Média",price:3000,minutes:60},{id:"l-long",label:"Longa",price:6000,minutes:60}]},{id:"q-size",label:"Qual tamanho das tranças?",kind:"single",required:true,options:[{id:"s-large",label:"Grossa",price:0,minutes:0},{id:"s-medium",label:"Média",price:4000,minutes:60},{id:"s-small",label:"Fina",price:8000,minutes:120}]},{id:"q-material",label:"Quem fornece o material?",kind:"single",required:true,options:[{id:"m-client",label:"Eu levo",price:0,minutes:0},{id:"m-pro",label:"A profissional fornece",price:4000,minutes:0}]},{id:"q-ref",label:"Tem uma foto de referência?",kind:"photo",required:false,options:[]}],Nagô:[question("Quantas tranças você deseja?","number"),question("Quer incluir desenhos?","yesno")],Twist:[question("Qual comprimento você prefere?","single",[{id:"t-medium",label:"Médio",price:0,minutes:0},{id:"t-long",label:"Longo",price:4000,minutes:60}])]};
const base:State={displayName:"Ana Martins",business:"Ana Tranças",city:"Rio Vermelho, Salvador",slug:"ana-trancas",description:"Tranças feitas com carinho e atenção a cada detalhe. Vamos encontrar o estilo ideal para você?",services:[{name:"Box braids",price:22000,duration:240,active:true,questions:templates["Box braids"]},{name:"Nagô",price:10000,duration:120,active:true,questions:templates.Nagô},{name:"Twist",price:18000,duration:180,active:true,questions:templates.Twist}],hours:["Segunda","Terça","Quarta","Quinta","Sexta","Sábado"].map((day,index)=>({day,enabled:index<5,start:"09:00",end:"18:00"})),appointments:[]};
function localDay(offset:number){const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()+offset);return date;}
function dateText(offset:number,opts:Intl.DateTimeFormatOptions={weekday:"long",day:"numeric",month:"long"}){return new Intl.DateTimeFormat("pt-BR",opts).format(localDay(offset));}
function formatMoney(cents:number){return`R$ ${(cents/100).toFixed(2).replace(".",",")}`;}
function normalize(raw:Partial<State>):State{const services=(raw.services??base.services).map(s=>({...s,price:s.price<10000?s.price*100:s.price,questions:s.questions??templates[s.name]??[]}));return{...base,...raw,services,hours:raw.hours??base.hours,appointments:(raw.appointments??base.appointments).map(a=>({...a,price:a.price??services.find(s=>s.name===a.service)?.price??0,duration:a.duration??services.find(s=>s.name===a.service)?.duration??120,answers:a.answers??[],history:a.history??[`${a.status} · item de demonstração.`]}))};}
function openSlots(data:State,service:Service,dayOffset:number,ignoreId?:string){const weekday=(localDay(dayOffset).getDay()+6)%7,rule=data.hours[weekday];if(!rule?.enabled)return[];const [sh,sm]=rule.start.split(":").map(Number),[eh,em]=rule.end.split(":").map(Number),from=sh*60+sm,to=eh*60+em,blocked=data.appointments.filter(a=>a.id!==ignoreId&&a.dayOffset===dayOffset&&a.status==="Confirmado").map(a=>{const [h,m]=a.time.split(":").map(Number),other=data.services.find(s=>s.name===a.service);const start=h*60+m;return[start,start+(other?.duration??a.duration??120)]});const slots:string[]=[];for(let n=from;n+service.duration<=to;n+=30)if(!blocked.some(([a,b])=>n<b&&n+service.duration>a))slots.push(`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`);return slots;}

export function LocalBookingDemo(){
 const [data,setData]=useState<State>(base),[loaded,setLoaded]=useState(false),[tab,setTab]=useState<"configurar"|"cliente"|"profissional"|"acompanhar"|"agenda">("configurar"),[serviceName,setServiceName]=useState("Box braids"),[questionText,setQuestionText]=useState(""),[questionKind,setQuestionKind]=useState<Kind>("single"),[optionText,setOptionText]=useState(""),[step,setStep]=useState(-1),[answers,setAnswers]=useState<Record<string,Answer>>({}),[day,setDay]=useState(1),[time,setTime]=useState(""),[client,setClient]=useState(""),[clientPhone,setClientPhone]=useState(""),[editingId,setEditingId]=useState<string|null>(null),[notice,setNotice]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setData(normalize(JSON.parse(raw)))}catch{}setLoaded(true);const sync=(event:StorageEvent)=>{if(event.key===KEY&&event.newValue){try{setData(normalize(JSON.parse(event.newValue)))}catch{}}};window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(KEY,JSON.stringify(data))},[data,loaded]);
 const service=data.services.find(s=>s.name===serviceName)??data.services[0];
 const chosenAnswers=useMemo(()=>service?.questions.map(q=>answers[q.id]).filter(Boolean) as Answer[]??[],[service,answers]);
 const quote=useMemo(()=>{let price=service?.price??0,minutes=service?.duration??0;for(const answer of chosenAnswers){const q=service?.questions.find(x=>x.id===answer.questionId);for(const option of q?.options??[])if(answer.optionIds.includes(option.id)){price+=option.price;minutes+=option.minutes;}}return{price,minutes};},[service,chosenAnswers]);
 const slots=openSlots(data,service?{...service,duration:quote.minutes}:base.services[0],day,editingId??undefined);
 const setAnswer=(q:Question,value:string,optionIds:string[]=[] )=>setAnswers(current=>({...current,[q.id]:{questionId:q.id,label:q.label,value,optionIds}}));
 function addQuestion(){if(!questionText.trim()||!service)return;const options=["single","multiple"].includes(questionKind)?optionText.split(",").map(s=>s.trim()).filter(Boolean).map((entry,i)=>{const[label,price="0",minutes="0"]=entry.split("|").map(x=>x.trim());return{id:`${Date.now()}-${i}`,label,price:Math.round(Number(price.replace(",","."))*100)||0,minutes:Math.round(Number(minutes))||0}}):[];if(["single","multiple"].includes(questionKind)&&!options.length)return;setData(current=>({...current,services:current.services.map(s=>s.name===service.name?{...s,questions:[...s.questions,question(questionText.trim(),questionKind,options)]}:s)}));setQuestionText("");setOptionText("");}
 function removeQuestion(id:string){if(!service)return;setData(current=>({...current,services:current.services.map(s=>s.name===service.name?{...s,questions:s.questions.filter(q=>q.id!==id)}:s)}));}
 function submitRequest(){if(!service||!client.trim()||!clientPhone.trim()||!time)return;const history=[`Cliente solicitou ${dateText(day)} às ${time}.`];if(editingId){setData(current=>({...current,appointments:current.appointments.map(a=>a.id===editingId?{...a,dayOffset:day,time,client:client.trim(),phone:clientPhone,status:"Nova solicitação",proposal:undefined,answers:chosenAnswers,price:quote.price,duration:quote.minutes,history:[...a.history,`Cliente pediu outro horário: ${dateText(day)} às ${time}.`]}:a)}));setNotice("Novo horário enviado para a profissional. A solicitação já está na lista dela.");setEditingId(null);}else{const appointment:Appointment={id:crypto.randomUUID(),dayOffset:day,time,client:client.trim(),phone:clientPhone,service:service.name,status:"Nova solicitação",price:quote.price,duration:quote.minutes,answers:chosenAnswers,history};setData(current=>({...current,appointments:[appointment,...current.appointments]}));setNotice("Solicitação enviada! A profissional já consegue ver seu pedido.");}setTab("acompanhar");setStep(-1);setTime("");}
 function professionalAction(id:string,status:string){setData(current=>({...current,appointments:current.appointments.map(a=>a.id===id?{...a,status,history:[...a.history,`${status} pela profissional.`]}:a)}));}
 function sendProposal(a:Appointment,proposedTime:string,proposedDay:number,proposedPrice:number,proposedDuration:number,note:string){setData(current=>({...current,appointments:current.appointments.map(x=>x.id===a.id?{...x,status:"Proposta enviada",proposal:{dayOffset:proposedDay,time:proposedTime,price:proposedPrice,duration:proposedDuration,note},history:[...x.history,`Profissional propôs ${dateText(proposedDay)} às ${proposedTime}, duração ${proposedDuration} min e preço ${formatMoney(proposedPrice)}.${note?` Mensagem: ${note}`:""}`]}:x)}));}
 function clientAction(a:Appointment,action:"accept"|"cancel"|"reschedule"){if(action==="reschedule"){setEditingId(a.id);setServiceName(a.service);setClient(a.client);setClientPhone(a.phone??"");setAnswers(Object.fromEntries(a.answers.map(answer=>[answer.questionId,answer])));setDay(a.proposal?.dayOffset??a.dayOffset);setTime("");setStep(-1);setTab("cliente");return;}setData(current=>({...current,appointments:current.appointments.map(x=>x.id===a.id?action==="accept"&&x.proposal?{...x,dayOffset:x.proposal.dayOffset,time:x.proposal.time,price:x.proposal.price,duration:x.proposal.duration,status:"Confirmado",proposal:undefined,history:[...x.history,"Cliente aceitou a proposta. Atendimento confirmado."]}:{...x,status:"Cancelado pela cliente",history:[...x.history,"Cliente cancelou a solicitação."]}:x)}));setNotice(action==="accept"?"Proposta aceita. Atendimento confirmado na agenda!":"Solicitação cancelada.");}
 function selectTab(value:typeof tab){setTab(value);setNotice("");}

 return <main className="local-demo-page"><header className="local-demo-header"><Link className="brand" href="/demo"><span className="brand-mark">t</span><span>Tá Marcado <small>· laboratório local</small></span></Link><span className="pill">Sem banco · salva neste navegador</span></header><div className="local-demo-wrap"><div className="trial-box"><b>Fluxo completo em modo local.</b> Os dados são fictícios e compartilhados entre a visão da cliente e da profissional neste navegador. Não há envio externo.</div><nav className="local-demo-tabs">{([["configurar","Perguntas do serviço"],["cliente","Cliente: solicitar"],["profissional","Profissional: responder"],["acompanhar","Cliente: acompanhar"],["agenda","Calendário"]] as const).map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>selectTab(key)}>{label}</button>)}</nav>
 {tab==="configurar"&&<section className="panel local-panel"><span className="eyebrow"><Settings2 size={13}/> Configuração do serviço</span><h1 className="serif">Perguntas para personalizar o atendimento</h1><p>As respostas entram no pedido da cliente e podem ajustar o orçamento. Experimente o modelo Box braids.</p><div className="form-field"><label htmlFor="question-service">Serviço</label><select id="question-service" value={serviceName} onChange={e=>setServiceName(e.target.value)}>{data.services.map(s=><option key={s.name}>{s.name}</option>)}</select></div><div className="demo-question-list">{service?.questions.map((q,index)=><article className="demo-question-card" key={q.id}><div><span className="status">Pergunta {index+1} · {q.kind}</span><h3>{q.label}{q.required&&" *"}</h3>{q.options.map(o=><span className="pill" key={o.id}>{o.label}{o.price?` · +${formatMoney(o.price)}`:""}{o.minutes?` · +${o.minutes} min`:""}</span>)}</div><button className="btn small secondary" onClick={()=>removeQuestion(q.id)}>Remover</button></article>)}</div><h2 className="serif">Adicionar pergunta</h2><div className="form-field"><label htmlFor="q-label">O que você quer perguntar?</label><input id="q-label" value={questionText} onChange={e=>setQuestionText(e.target.value)} placeholder="Ex.: Qual cor você prefere?"/></div><div className="form-field"><label htmlFor="q-kind">Tipo de resposta</label><select id="q-kind" value={questionKind} onChange={e=>setQuestionKind(e.target.value as Kind)}><option value="single">Escolha única</option><option value="multiple">Múltipla escolha</option><option value="text">Texto</option><option value="number">Número</option><option value="yesno">Sim ou não</option><option value="photo">Foto de referência</option></select></div>{["single","multiple"].includes(questionKind)&&<div className="form-field"><label htmlFor="q-options">Opções com ajustes (separadas por vírgula)</label><input id="q-options" value={optionText} onChange={e=>setOptionText(e.target.value)} placeholder="Curta | 0 | 0, Longa | 60 | 60"/><small>Formato: opção | acréscimo em R$ | minutos extras. Ex.: Longa | 60 | 60.</small></div>}<button className="btn" onClick={addQuestion}><Plus size={15}/> Adicionar pergunta</button><button className="btn secondary" style={{marginLeft:9}} onClick={()=>selectTab("cliente")}>Ver como cliente <ArrowRight size={15}/></button></section>}

 {tab==="cliente"&&<section className="panel local-panel"><div className="demo-public-head"><span className="brand-mark">{data.displayName.slice(0,1)}</span><div><b>{data.displayName} · Trancista</b><small>{data.city}</small></div></div>{editingId&&<p className="trial-box">Você está escolhendo outro horário para uma solicitação já existente.</p>}<h1 className="serif">Vamos montar seu atendimento</h1><div className="progress-steps">{Array.from({length:(service?.questions.length??0)+3},(_,i)=><span key={i} className={step>=i-1?"on":""}/>)}</div>
 {step===-1&&<div className="form-field"><label>Qual serviço você quer?</label><div className="demo-service-choices">{data.services.filter(s=>s.active).map(s=><button key={s.name} className={`demo-service-choice ${service?.name===s.name?"selected":""}`} onClick={()=>{setServiceName(s.name);setAnswers({});setTime("")}}><b>{s.name}</b><span>A partir de {formatMoney(s.price)} · {Math.floor(s.duration/60)}h</span></button>)}</div></div>}
 {step>=0&&step<(service?.questions.length??0)&&(()=>{const q=service!.questions[step],a=answers[q.id];return <div className="form-field"><label>{q.label}{q.required?" *":""}</label>{q.kind==="single"&&q.options.map(o=><label className="demo-answer-option" key={o.id}><input type="radio" name={q.id} checked={a?.optionIds.includes(o.id)??false} onChange={()=>setAnswer(q,o.label,[o.id])}/><span>{o.label}{o.price?` · +${formatMoney(o.price)}`:""}{o.minutes?` · +${o.minutes} min`:""}</span></label>)}{q.kind==="multiple"&&q.options.map(o=><label className="demo-answer-option" key={o.id}><input type="checkbox" checked={a?.optionIds.includes(o.id)??false} onChange={e=>{const ids=a?.optionIds??[];setAnswer(q,[...ids.filter(id=>id!==o.id),...(e.target.checked?[o.id]:[])].map(id=>q.options.find(x=>x.id===id)?.label).filter(Boolean).join(", "),e.target.checked?[...ids,o.id]:ids.filter(id=>id!==o.id))}}/><span>{o.label}{o.price?` · +${formatMoney(o.price)}`:""}{o.minutes?` · +${o.minutes} min`:""}</span></label>)}{q.kind==="yesno"&&<select value={a?.value??""} onChange={e=>setAnswer(q,e.target.value)}><option value="">Escolha uma opção</option><option>Sim</option><option>Não</option></select>}{(q.kind==="text"||q.kind==="number")&&<input type={q.kind} value={a?.value??""} onChange={e=>setAnswer(q,e.target.value)}/ >}{q.kind==="photo"&&<input type="file" accept="image/*" onChange={e=>setAnswer(q,e.target.files?.[0]?.name??"")}/ >}</div>})()}
 {step===(service?.questions.length??0)&&<><div className="form-field"><label>Escolha um dia</label><select value={day} onChange={e=>{setDay(Number(e.target.value));setTime("")}}>{Array.from({length:14},(_,i)=>i).map(offset=><option key={offset} value={offset}>{dateText(offset)}</option>)}</select></div><div className="form-field"><label>Horários disponíveis · {service?.duration?`${Math.floor(quote.minutes/60)}h${quote.minutes%60?` ${quote.minutes%60}min`:""}`:""}</label><div className="demo-slots">{slots.length?slots.map(slot=><button type="button" key={slot} className={`pill ${time===slot?"selected":""}`} onClick={()=>setTime(slot)}>{slot}</button>):<span>Sem horários livres nesse dia; escolha outra data.</span>}</div></div></>}
 {step===(service?.questions.length??0)+1&&<><div className="demo-quote"><div><span>Estimativa</span><b>{formatMoney(quote.price)}</b></div><div><span>Duração</span><b>{Math.floor(quote.minutes/60)}h{quote.minutes%60?` ${quote.minutes%60}min`:""}</b></div></div><div className="form-field"><label htmlFor="client-name">Seu nome</label><input id="client-name" value={client} onChange={e=>setClient(e.target.value)} placeholder="Ex.: Bruna Souza"/></div><div className="form-field"><label htmlFor="client-phone">WhatsApp</label><input id="client-phone" value={clientPhone} onChange={e=>setClientPhone(e.target.value)} placeholder="(71) 99999-9999"/></div><p>Confira suas respostas:</p>{chosenAnswers.map(a=><p key={a.questionId}><b>{a.label}</b> {a.value}</p>)}</>}
 <div className="local-flow-actions">{step>-1&&<button className="btn secondary" onClick={()=>setStep(step-1)}><ArrowLeft size={14}/> Voltar</button>}{step<(service?.questions.length??0)+1?<button className="btn" onClick={()=>{if(step===(service?.questions.length??0)&&!time){setNotice("Escolha um horário para continuar.");return}const q=step>=0?service?.questions[step]:null;if(q?.required&&!answers[q.id]){setNotice("Responda à pergunta para continuar.");return}setNotice("");setStep(step+1)}}>Continuar <ArrowRight size={14}/></button>:<button className="btn" disabled={!client.trim()||!clientPhone.trim()||!time} onClick={submitRequest}><Send size={14}/> Enviar solicitação</button>}</div>{notice&&<p className="form-error" role="alert">{notice}</p>}<p className="demo-disclaimer">Você não precisa criar conta. Esta solicitação é local e só aparece nesta demonstração.</p></section>}

 {tab==="profissional"&&<section className="panel local-panel"><h1 className="serif">Solicitações para responder</h1>{data.appointments.filter(a=>["Nova solicitação","Aguardando resposta"].includes(a.status)).length?data.appointments.filter(a=>["Nova solicitação","Aguardando resposta"].includes(a.status)).map(a=><ProfessionalRequest key={a.id} appointment={a} data={data} onConfirm={()=>professionalAction(a.id,"Confirmado")} onReject={()=>professionalAction(a.id,"Recusado pela profissional")} onPropose={(t,d,p,m,n)=>sendProposal(a,t,d,p,m,n)}/>):<p>Nenhum pedido aguardando. Envie uma solicitação na aba Cliente para testar o fluxo.</p>}</section>}

 {tab==="acompanhar"&&<section className="panel local-panel"><h1 className="serif">Acompanhar meu pedido</h1>{notice&&<p className="trial-box" role="status">{notice}</p>}{data.appointments.map(a=><article className="demo-booking-card" key={a.id}><div className="panel-title"><span>{a.service} · {a.status}</span><span className="status">{formatMoney(a.proposal?.price??a.price)}</span></div><p><CalendarDays size={14}/> {dateText(a.proposal?.dayOffset??a.dayOffset)} às {a.proposal?.time??a.time} · {a.proposal?.duration??a.duration} min</p>{a.proposal?.note&&<p className="trial-box">Mensagem da profissional: {a.proposal.note}</p>}{a.answers.map(x=><p key={x.questionId}><b>{x.label}</b> {x.value}</p>)}<div className="demo-history"><b>Atualizações</b>{a.history.map((item,i)=><small key={`${a.id}-${i}`}>{item}</small>)}</div>{a.status==="Proposta enviada"&&a.proposal&&<div className="local-flow-actions"><button className="btn" onClick={()=>clientAction(a,"accept")}><Check size={14}/> Aceitar novo horário</button><button className="btn secondary" onClick={()=>clientAction(a,"reschedule")}><CalendarDays size={14}/> Escolher outro horário</button><button className="btn secondary" onClick={()=>clientAction(a,"cancel")} >Cancelar</button></div>}{["Nova solicitação","Aguardando resposta","Confirmado"].includes(a.status)&&<button className="btn secondary" onClick={()=>clientAction(a,"cancel")}>Cancelar solicitação</button>}</article>)}</section>}

 {tab==="agenda"&&<section className="panel local-panel"><h1 className="serif">Calendário da profissional</h1><div className="demo-week">{Array.from({length:7},(_,offset)=><div className="demo-day" key={offset}><span>{dateText(offset,{weekday:"short"})}</span><b>{dateText(offset,{day:"numeric"})}</b><small>{data.appointments.filter(a=>a.dayOffset===offset&&a.status==="Confirmado").length} confirmado(s)</small></div>)}</div>{Array.from({length:7},(_,offset)=><div className="demo-calendar-day" key={offset}><h3>{dateText(offset)}</h3>{data.appointments.filter(a=>a.dayOffset===offset&&a.status!=="Cancelado pela cliente"&&a.status!=="Recusado pela profissional").sort((a,b)=>a.time.localeCompare(b.time)).map(a=><div className={`demo-event ${a.status==="Confirmado"?"confirmed":"pending"}`} key={a.id}><b>{a.time} · {a.client}</b><span>{a.service} · {a.status} · {formatMoney(a.price)}</span></div>)}{!data.appointments.some(a=>a.dayOffset===offset)&&<small>Sem marcações neste dia.</small>}</div>)}</section>}
 <footer className="local-demo-footer"><Link href="/demo">← Voltar ao painel de Ana Tranças</Link><span><Clock3 size={13}/> Atualização local imediata · localStorage do navegador</span></footer></div></main>;
}

function ProfessionalRequest({appointment:a,data,onConfirm,onReject,onPropose}:{appointment:Appointment;data:State;onConfirm:()=>void;onReject:()=>void;onPropose:(time:string,day:number,price:number,duration:number,note:string)=>void}){
 const [editing,setEditing]=useState(false),[day,setDay]=useState(a.dayOffset),[time,setTime]=useState(a.time),[price,setPrice]=useState(a.price/100),[duration,setDuration]=useState(a.duration),[question,setQuestion]=useState("");const service=data.services.find(s=>s.name===a.service)??data.services[0];const slots=openSlots(data,{...service,duration},day,a.id);
 return <article className="demo-booking-card"><div className="panel-title"><span>{a.client} · {a.service}</span><span className="status">{a.status}</span></div><p><CalendarDays size={14}/> Pediu {dateText(a.dayOffset)} às {a.time} · estimativa {formatMoney(a.price)} · {a.duration} min</p>{a.phone&&<p><UserRound size={13}/> {a.phone}</p>}{a.answers.map(answer=><p key={answer.questionId}><b>{answer.label}</b> {answer.value}</p>)}<div className="demo-history"><b>Histórico</b>{a.history.map((item,i)=><small key={`${a.id}-h${i}`}>{item}</small>)}</div>{!editing?<div className="local-flow-actions"><button className="btn" onClick={onConfirm}><Check size={14}/> Confirmar como solicitado</button><button className="btn secondary" onClick={()=>setEditing(true)}>Propor outro horário/valor</button><button className="btn secondary" onClick={onReject}>Recusar</button></div>:<div className="demo-proposal"><h3>Enviar uma proposta</h3><div className="form-field"><label>Novo dia</label><select value={day} onChange={e=>{setDay(Number(e.target.value));setTime("")}}>{Array.from({length:14},(_,i)=><option key={i} value={i}>{dateText(i)}</option>)}</select></div><div className="form-field"><label>Horário disponível</label><select value={time} onChange={e=>setTime(e.target.value)}><option value="">Escolha</option>{slots.map(slot=><option key={slot}>{slot}</option>)}</select></div><div className="form-field"><label>Preço combinado (R$)</label><input type="number" step="0.01" min="0" value={price} onChange={e=>setPrice(Number(e.target.value))}/></div><div className="form-field"><label>Duração acordada (minutos)</label><input type="number" min="15" step="15" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></div><div className="form-field"><label>Observação para a cliente</label><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ex.: consigo te atender um pouco mais cedo"/></div><button className="btn" disabled={!time} onClick={()=>onPropose(time,day,Math.round(price*100),duration,question)}><Send size={14}/> Enviar proposta</button><button className="btn secondary" style={{marginLeft:8}} onClick={()=>setEditing(false)}>Voltar</button></div>}</article>;
}
