"use client";

import { FormEvent,useState } from "react";
import { Plus } from "lucide-react";
import { useRouter } from "next/navigation";

type Service={id:string;name:string;base_price_cents:number|null;base_duration_minutes:number|null};
export function ManualAppointment({services}:{services:Service[]}){
 const [open,setOpen]=useState(false);const [error,setError]=useState("");const [pending,setPending]=useState(false);const router=useRouter();
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);setPending(true);try{const response=await fetch("/api/appointments/manual",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),phone:form.get("phone"),serviceId:form.get("serviceId"),date:form.get("date"),time:form.get("time"),price:form.get("price")||undefined,duration:form.get("duration")||undefined,note:form.get("note")})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Não foi possível salvar o atendimento.");setOpen(false);router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível salvar o atendimento.")}finally{setPending(false)}}
 return <><button className="btn" onClick={()=>setOpen(!open)}><Plus size={15}/> Novo atendimento</button>{open&&<form className="panel" style={{position:"fixed",zIndex:30,right:18,top:82,width:"min(520px, calc(100vw - 36px))",maxHeight:"calc(100vh - 100px)",overflowY:"auto",boxShadow:"0 18px 60px #44273325"}} onSubmit={save}><div className="panel-title"><span>Novo atendimento manual</span><button type="button" className="pill" onClick={()=>setOpen(false)}>Fechar</button></div><p style={{fontSize:12,color:"var(--muted)"}}>Registros manuais não consomem seus atendimentos gratuitos.</p><div className="form-field"><label htmlFor="manual-name">Cliente</label><input id="manual-name" name="name" required minLength={2}/></div><div className="form-field"><label htmlFor="manual-phone">WhatsApp</label><input id="manual-phone" name="phone" type="tel" required minLength={10}/></div><div className="form-field"><label htmlFor="manual-service">Serviço</label><select id="manual-service" name="serviceId" required defaultValue=""><option value="" disabled>Escolha um serviço</option>{services.map(service=><option key={service.id} value={service.id}>{service.name}</option>)}</select></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr"}}><div className="form-field"><label htmlFor="manual-date">Dia</label><input id="manual-date" name="date" type="date" min={new Date().toLocaleDateString("en-CA")} required/></div><div className="form-field"><label htmlFor="manual-time">Horário</label><input id="manual-time" name="time" type="time" required/></div></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr"}}><div className="form-field"><label htmlFor="manual-price">Valor final (R$)</label><input id="manual-price" name="price" type="number" min="0" step="0.01"/></div><div className="form-field"><label htmlFor="manual-duration">Duração (min)</label><input id="manual-duration" name="duration" type="number" min="1" max="1440"/></div></div><div className="form-field"><label htmlFor="manual-note">Observação interna</label><textarea id="manual-note" name="note" maxLength={500}/></div>{error&&<p className="form-error">{error}</p>}<button className="btn" disabled={pending}>{pending?"Salvando…":"Confirmar atendimento"}</button></form>}</>;
}
