"use client";
import { BrandLogo } from "@/components/brand-logo";

import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Copy } from "lucide-react";
import Link from "next/link";

const categoryOptions=["Tranças","Unhas","Cílios","Sobrancelhas","Depilação","Maquiagem","Cabelo","Estética"];
const categorySlugs=["trancas","unhas","cilios","sobrancelhas","depilacao","maquiagem","cabelo","estetica"];

export function OnboardingForm({initialName}:{initialName:string}) {
 const [step,setStep]=useState(0);const [categories,setCategories]=useState<string[]>([]);const [error,setError]=useState("");const [pending,setPending]=useState(false);const [result,setResult]=useState("");const [draft,setDraft]=useState<Record<string,string>>({});
 function toggle(category:string){setCategories(old=>old.includes(category)?old.filter(x=>x!==category):[...old,category])}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);const values={...draft,...Object.fromEntries(data.entries())};const rawSlug=String(values.slug??"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(rawSlug.length<3){setError("Escolha um link com pelo menos 3 caracteres.");return}if(categories.length===0){setError("Escolha ao menos uma categoria.");return}setPending(true);try{const response=await fetch("/api/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:values.business,displayName:values.display,phone:values.whatsapp,slug:rawSlug,categories:categories.map(c=>categorySlugs[categoryOptions.indexOf(c)]),service:values.service,price:values.price,duration:values.duration,description:values.description??"",start:values.start,end:values.end,city:values.city})});const json=await response.json();if(!response.ok)throw new Error(json.error??"Não foi possível salvar seu espaço.");setResult(json.url??`/${rawSlug}`)}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar seu espaço.")}finally{setPending(false)}}
 if(result)return <section className="form-card" style={{textAlign:"center"}}><span className="brand-mark" style={{margin:"0 auto",width:50,height:50,fontSize:27}}><Check/></span><span className="eyebrow" style={{display:"block",marginTop:18}}>Tudo pronto</span><h1>Seu Tá Marcado está pronto!</h1><p>Agora você pode compartilhar sua página com suas clientes.</p><div className="trial-box" style={{textAlign:"left",fontSize:14,fontWeight:700}}>{typeof window!=="undefined"?window.location.origin:"tamarcado.com.br"}{result}</div><button className="btn" style={{width:"100%",marginTop:15}} onClick={()=>navigator.clipboard.writeText(`${window.location.origin}${result}`)}><Copy size={15}/> Copiar link</button><a className="btn secondary" style={{width:"100%",marginTop:9}} href={result} target="_blank">Ver minha página <ArrowRight size={14}/></a><a className="btn secondary" style={{width:"100%",marginTop:9}} href="/app">Ir para minha agenda</a></section>;
 return <form className="form-card" id="onboarding-form" onChange={event=>{const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement)setDraft(current=>({...current,[target.name]:target.value}))}} onSubmit={submit}><a href="/" className="brand"><BrandLogo /></a><div style={{marginTop:24}}><span className="eyebrow">Vamos preparar seu espaço · {step+1}/5</span><h1>{["Sobre você","O que você faz","Seu primeiro serviço","Quando você atende","Sua página"][step]}</h1><p>Você pode mudar essas informações depois.</p></div><div className="progress-steps">{[0,1,2,3,4].map(i=><span className={step>=i?"on":""} key={i}/>)}</div>
 {step===0&&<><div className="form-field"><label htmlFor="display">Seu nome profissional</label><input id="display" name="display" defaultValue={draft.display??initialName} placeholder="Como suas clientes conhecem você?" required minLength={2}/></div><div className="form-field"><label htmlFor="business">Nome do seu espaço ou negócio</label><input id="business" name="business" defaultValue={draft.business} placeholder="Ex.: Ana Tranças" required minLength={2}/></div><div className="form-field"><label htmlFor="whatsapp">WhatsApp</label><input id="whatsapp" name="whatsapp" type="tel" defaultValue={draft.whatsapp} placeholder="(71) 99999-9999" required minLength={10}/></div></>}
 {step===1&&<><p>Marque todas as opções que combinam com seu trabalho.</p><div className="service-chips">{categoryOptions.map(c=><button type="button" className="pill" style={{background:categories.includes(c)?"var(--green)":"#f5e6eb",color:categories.includes(c)?"white":"var(--green)"}} onClick={()=>toggle(c)} key={c}>{c}</button>)}</div></>}
 {step===2&&<><div className="form-field"><label htmlFor="service">Qual serviço você oferece?</label><input id="service" name="service" defaultValue={draft.service} placeholder="Ex.: Box braids" required minLength={2}/></div><div className="form-field"><label htmlFor="price">Preço base (R$)</label><input id="price" name="price" type="number" min="0" step="0.01" defaultValue={draft.price} placeholder="220,00" required/></div><div className="form-field"><label htmlFor="duration">Duração aproximada</label><select id="duration" name="duration" defaultValue={draft.duration??"240"}><option value="60">1 hora</option><option value="90">1h30</option><option value="120">2 horas</option><option value="180">3 horas</option><option value="240">4 horas</option><option value="300">5 horas</option><option value="360">6 horas</option></select></div></>}
 {step===3&&<><p>Uma disponibilidade inicial para sua agenda. Você ajusta dia por dia depois.</p><div className="form-field"><label htmlFor="start">Começo do expediente</label><input id="start" name="start" type="time" defaultValue={draft.start??"09:00"} required/></div><div className="form-field"><label htmlFor="end">Fim do expediente</label><input id="end" name="end" type="time" defaultValue={draft.end??"18:00"} required/></div><div className="form-field"><label htmlFor="city">Cidade ou região atendida</label><input id="city" name="city" defaultValue={draft.city} placeholder="Ex.: Rio Vermelho, Salvador"/></div></>}
 {step===4&&<><div className="form-field"><label htmlFor="slug">Seu link exclusivo</label><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:12,color:"var(--muted)"}}>tamarcado.com.br/</span><input id="slug" name="slug" defaultValue={draft.slug} placeholder="seu-nome" required minLength={3}/></div></div><div className="form-field"><label htmlFor="description">Conte um pouquinho sobre seu trabalho</label><textarea id="description" name="description" defaultValue={draft.description} rows={4} maxLength={500} placeholder="O que suas clientes precisam saber?"/></div><p style={{fontSize:12,color:"var(--muted)"}}>Sua página ficará pública quando você concluir. Endereço residencial não será exibido.</p></>}
 {error&&<p className="form-error" role="alert">{error}</p>}<div style={{display:"flex",gap:10,marginTop:23}}>{step>0&&<button type="button" className="btn secondary" onClick={()=>setStep(step-1)}><ArrowLeft size={14}/> Voltar</button>}{step<4?<button type="button" className="btn" style={{flex:1}} onClick={()=>{const form=document.getElementById("onboarding-form");if(step===0&&!form?.querySelector<HTMLInputElement>("[name=display]")?.reportValidity())return;if(step===0&&!form?.querySelector<HTMLInputElement>("[name=business]")?.reportValidity())return;if(step===0&&!form?.querySelector<HTMLInputElement>("[name=whatsapp]")?.reportValidity())return;if(step===2&&!form?.querySelector<HTMLInputElement>("[name=service]")?.reportValidity())return;if(step===2&&!form?.querySelector<HTMLInputElement>("[name=price]")?.reportValidity())return;if(step===3&&!form?.querySelector<HTMLInputElement>("[name=start]")?.reportValidity())return;if(step===3&&!form?.querySelector<HTMLInputElement>("[name=end]")?.reportValidity())return;if(step===1&&!categories.length){setError("Escolha ao menos uma categoria.");return}setError("");setStep(step+1)}}>Continuar <ArrowRight size={14}/></button>:<button className="btn" style={{flex:1}} disabled={pending}>{pending?"Preparando sua página…":"Publicar minha página"} <Check size={15}/></button>}</div></form>;
}
