"use client";

import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { Plus,Scissors,Trash2 } from "lucide-react";

type Option={key:string;label:string;priceDelta:string;durationDelta:string};
type Question={key:string;label:string;type:string;required:boolean;options:Option[]};
const choices=new Set(["single_choice","multiple_choice"]);
const newOption=():Option=>({key:crypto.randomUUID(),label:"",priceDelta:"0",durationDelta:"0"});
const newQuestion=():Question=>({key:crypto.randomUUID(),label:"",type:"single_choice",required:false,options:[newOption()]});

export function ServiceManager(){
 const router=useRouter();const [open,setOpen]=useState(false);const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [questions,setQuestions]=useState<Question[]>([]);
 function changeQuestion(key:string,update:Partial<Question>){setQuestions(current=>current.map(question=>question.key===key?{...question,...update}:question))}
 function changeOption(questionKey:string,optionKey:string,update:Partial<Option>){setQuestions(current=>current.map(question=>question.key===questionKey?{...question,options:question.options.map(option=>option.key===optionKey?{...option,...update}:option)}:question))}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);setSaving(true);try{const response=await fetch("/api/services",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),description:form.get("description"),price:form.get("price")||null,duration:form.get("duration")||null,buffer:form.get("buffer")||0,mode:form.get("mode"),questions:questions.map(question=>({label:question.label,type:question.type,required:question.required,options:question.options.map(option=>({label:option.label,priceDelta:option.priceDelta||0,durationDelta:option.durationDelta||0}))}))})});const result=await response.json();if(!response.ok)throw new Error(result.error);setOpen(false);setQuestions([]);router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível salvar o serviço.")}finally{setSaving(false)}}
 return <><button className="btn" onClick={()=>setOpen(!open)}><Plus size={15}/>{open?"Fechar":"Novo serviço"}</button>{open&&<form className="panel" style={{marginTop:16}} onSubmit={save}><div className="panel-title"><Scissors size={17}/> Detalhes do serviço</div><div className="form-field"><label htmlFor="service-name">Nome</label><input id="service-name" name="name" minLength={2} maxLength={120} required placeholder="Ex.: Box braids"/></div><div className="form-field"><label htmlFor="service-description">Descrição</label><textarea id="service-description" name="description" rows={3} maxLength={1000}/></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr"}}><div className="form-field"><label htmlFor="service-price">Preço base (R$)</label><input id="service-price" name="price" type="number" min="0" step="0.01" placeholder="Deixe vazio para combinar"/></div><div className="form-field"><label htmlFor="service-duration">Duração em minutos</label><input id="service-duration" name="duration" type="number" min="1" max="1440" placeholder="Deixe vazio para avaliar"/></div></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr"}}><div className="form-field"><label htmlFor="service-buffer">Intervalo/preparação (min)</label><input id="service-buffer" name="buffer" type="number" min="0" max="240" defaultValue="0"/></div><div className="form-field"><label htmlFor="service-mode">Como funciona o agendamento?</label><select id="service-mode" name="mode"><option value="approval">Confirmo cada solicitação</option><option value="instant">Confirmação automática</option><option value="evaluation">Avalio antes de combinar</option></select></div></div>
 <div className="panel" style={{marginTop:14}}><div className="panel-title"><span>Perguntas para personalizar</span><button type="button" className="pill" onClick={()=>setQuestions(current=>[...current,newQuestion()])}><Plus size={13}/> Adicionar pergunta</button></div><p style={{fontSize:12,color:"var(--muted)"}}>As opções podem alterar o preço e o tempo. O cálculo final acontece no sistema.</p>{questions.map((question,index)=><article key={question.key} style={{padding:"15px 0",borderTop:"1px solid var(--line)"}}><div className="panel-title"><span>Pergunta {index+1}</span><button type="button" aria-label="Remover pergunta" className="pill" onClick={()=>setQuestions(current=>current.filter(item=>item.key!==question.key))}><Trash2 size={13}/></button></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr"}}><div className="form-field"><label>Pergunta</label><input value={question.label} maxLength={200} onChange={event=>changeQuestion(question.key,{label:event.target.value})} placeholder="Ex.: Qual comprimento você prefere?" required/></div><div className="form-field"><label>Tipo de resposta</label><select value={question.type} onChange={event=>changeQuestion(question.key,{type:event.target.value,options:choices.has(event.target.value)?question.options:[ ]})}><option value="single_choice">Escolha uma opção</option><option value="multiple_choice">Escolha várias</option><option value="text">Texto</option><option value="number">Número</option><option value="boolean">Sim ou não</option><option value="note">Observação</option></select></div></div><label style={{display:"flex",gap:8,alignItems:"center",fontSize:12,margin:"8px 0 12px"}}><input type="checkbox" checked={question.required} onChange={event=>changeQuestion(question.key,{required:event.target.checked})}/> Resposta obrigatória</label>{choices.has(question.type)&&<div style={{paddingLeft:12,borderLeft:"2px solid var(--line)"}}>{question.options.map((option,optionIndex)=><div key={option.key} className="option-row"><input aria-label={`Opção ${optionIndex+1}`} value={option.label} onChange={event=>changeOption(question.key,option.key,{label:event.target.value})} placeholder={`Opção ${optionIndex+1}`} required/><input aria-label="Adicional de preço em reais" type="number" step="0.01" value={option.priceDelta} onChange={event=>changeOption(question.key,option.key,{priceDelta:event.target.value})} placeholder="+ R$"/><input aria-label="Adicional de duração em minutos" type="number" value={option.durationDelta} onChange={event=>changeOption(question.key,option.key,{durationDelta:event.target.value})} placeholder="+ min"/></div>)}<button type="button" className="btn secondary small" onClick={()=>changeQuestion(question.key,{options:[...question.options,newOption()]})}>Adicionar opção</button></div>}</article>)}</div>{error&&<p className="form-error">{error}</p>}<button className="btn" style={{marginTop:14}} disabled={saving}>{saving?"Salvando…":"Salvar serviço"}</button></form>}</>;
}
