"use client";

import { useRef, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { Check, Copy, ExternalLink, Share2 } from "lucide-react";

export function SharePage({url}:{url:string}){
 const [copied,setCopied]=useState(false);const [message,setMessage]=useState("");const qrRef=useRef<HTMLDivElement>(null);
 async function copy(){try{await navigator.clipboard.writeText(url);setCopied(true);setMessage("Link copiado.");setTimeout(()=>setCopied(false),1800)}catch{setMessage("Não foi possível copiar. Selecione o link para copiar manualmente.")}}
 async function share(){if(!navigator.share){await copy();return}try{await navigator.share({title:"Meu Tá Marcado",text:"Conheça meu trabalho e escolha um horário.",url})}catch{/* A pessoa fechou o menu de compartilhamento. */}}
 function downloadQr(){const svg=qrRef.current?.querySelector("svg");if(!svg)return;const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:"image/svg+xml;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="meu-ta-marcado.svg";link.click();URL.revokeObjectURL(link.href)}
 return <div className="share-grid"><section className="panel"><span className="eyebrow">Seu link público</span><h2 className="serif" style={{fontSize:29}}>Compartilhe seu trabalho.</h2><p style={{fontSize:13,color:"var(--muted)",lineHeight:1.65}}>Coloque o link na bio do Instagram, envie no WhatsApp ou deixe suas clientes acessarem seus serviços por conta própria.</p><div className="quick-action" style={{display:"flex",gap:8,alignItems:"center",justifyContent:"space-between",overflowWrap:"anywhere"}}><a href={url} target="_blank" rel="noreferrer" style={{fontSize:12}}>{url}</a><button aria-label="Copiar endereço" className="pill" onClick={copy}><Copy size={14}/></button></div><div style={{display:"flex",gap:9,flexWrap:"wrap",marginTop:15}}><button className="btn" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?"Copiado":"Copiar link"}</button><button className="btn secondary" onClick={share}><Share2 size={15}/> Compartilhar</button><a className="btn secondary" href={url} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Ver minha página</a></div>{message&&<p role="status" style={{fontSize:12,color:"var(--green2)"}}>{message}</p>}</section><section className="panel qr-panel"><span className="eyebrow">Seu QR Code</span><div ref={qrRef} style={{background:"white",padding:15,borderRadius:15,display:"inline-block",marginTop:14}}><QRCodeSVG value={url} size={184} level="H" includeMargin/></div><p style={{fontSize:12,color:"var(--muted)",maxWidth:235,lineHeight:1.6}}>Salve ou imprima para colocar no seu espaço.</p><button className="btn secondary small" onClick={downloadQr}>Baixar QR Code</button></section></div>;
}
