import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

function detectedImage(buffer:Uint8Array){if(buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff)return "image/jpeg";if(buffer[0]===0x89&&buffer[1]===0x50&&buffer[2]===0x4e&&buffer[3]===0x47)return "image/png";if(String.fromCharCode(...buffer.slice(0,4))==="RIFF"&&String.fromCharCode(...buffer.slice(8,12))==="WEBP")return "image/webp";return null}

export async function POST(request:Request){
 const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return NextResponse.json({error:"Não foi possível enviar esta imagem."},{status:403});
 const supabase=await createClient();if(!supabase)return NextResponse.json({error:"Entre na sua conta para continuar."},{status:401});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Entre na sua conta para continuar."},{status:401});
 const {data:member}=await supabase.from("business_members").select("business_id").eq("user_id",user.id).limit(1).maybeSingle();if(!member)return NextResponse.json({error:"Seu espaço não foi encontrado."},{status:404});
 let form:FormData;try{form=await request.formData()}catch{return NextResponse.json({error:"Escolha uma imagem válida."},{status:400})}const file=form.get("image");if(!(file instanceof File)||file.size<1||file.size>5*1024*1024)return NextResponse.json({error:"A imagem deve ter até 5 MB."},{status:400});
 const bytes=new Uint8Array(await file.arrayBuffer());const mime=detectedImage(bytes);if(!mime||mime!==file.type)return NextResponse.json({error:"Use uma imagem JPG, PNG ou WebP válida."},{status:400});const extension=mime==="image/jpeg"?"jpg":mime.slice(6);const path=`${member.business_id}/${randomUUID()}.${extension}`;
 const {error:uploadError}=await supabase.storage.from("portfolio").upload(path,bytes,{contentType:mime,cacheControl:"3600",upsert:false});if(uploadError)return NextResponse.json({error:"Não foi possível guardar a imagem."},{status:400});
 const {data,error}=await supabase.from("portfolio_items").insert({business_id:member.business_id,storage_path:path,alt_text:String(form.get("alt")??"").slice(0,200),is_public:true}).select("id,storage_path,alt_text").single();if(error){await supabase.storage.from("portfolio").remove([path]);return NextResponse.json({error:"Não foi possível adicionar a imagem ao portfólio."},{status:400})}
 return NextResponse.json({ok:true,item:data},{status:201});
}

export async function DELETE(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return NextResponse.json({error:"Não foi possível remover esta imagem."},{status:403});const supabase=await createClient();if(!supabase)return NextResponse.json({error:"Entre na sua conta para continuar."},{status:401});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Entre na sua conta para continuar."},{status:401});let raw:unknown;try{raw=await request.json()}catch{return NextResponse.json({error:"Imagem inválida."},{status:400})}if(typeof raw!=="object"||raw===null||!("id"in raw)||typeof raw.id!=="string")return NextResponse.json({error:"Imagem inválida."},{status:400});const {data:item,error:lookupError}=await supabase.from("portfolio_items").select("id,storage_path").eq("id",raw.id).single();if(lookupError||!item)return NextResponse.json({error:"Imagem não encontrada."},{status:404});const {error:deleteError}=await supabase.from("portfolio_items").delete().eq("id",item.id);if(deleteError)return NextResponse.json({error:"Não foi possível remover a imagem."},{status:400});await supabase.storage.from("portfolio").remove([item.storage_path]);return NextResponse.json({ok:true})}
