import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default async function LoginPage({searchParams}:{searchParams:Promise<{erro?:string;cadastro?:string}>}) {
  const {erro,cadastro}=await searchParams;
  const error=erro==="limite"?"Muitas tentativas de acesso. Aguarde alguns minutos e tente novamente.":erro==="credentials"?"E-mail ou senha inválidos.":erro==="confirmar-email"?"Confirme seu e-mail pelo link que enviamos antes de entrar. Confira também a pasta de spam.":erro==="config"?"O acesso está temporariamente indisponível.":erro==="reenvio-limite"?"Muitas tentativas de reenvio. Aguarde alguns minutos e tente novamente.":erro==="reenvio"?"Não foi possível reenviar agora. Confira o e-mail e tente novamente em alguns minutos.":erro?"Confira os dados e tente novamente.":"";
  const showingConfirmation=cadastro==="confirme-email"||cadastro==="reenvio-enviado"||erro==="confirmar-email"||erro==="reenvio"||erro==="reenvio-limite";
  return <main className="form-wrap"><form className="form-card" action="/api/auth/login" method="post"><Link href="/" style={{fontSize:12,color:"var(--muted)"}}><ArrowLeft size={14}/> Voltar ao início</Link><div style={{marginTop:26}}><span className="eyebrow">Acesso profissional</span><h1>Entre no seu espaço.</h1><p>Acesse sua agenda e continue de onde parou.</p></div>{cadastro==="confirme-email"&&<div className="auth-confirm-notice" role="status"><b>Cadastro iniciado. Confirme seu e-mail para continuar.</b><span>Enviamos um link para o endereço informado. Abra esse link para entrar e seguir para a configuração do seu espaço profissional. Se não encontrar, confira a pasta de spam.</span></div>}{cadastro==="reenvio-enviado"&&<div className="auth-confirm-notice" role="status"><b>Confira sua caixa de entrada.</b><span>Se este endereço estiver aguardando confirmação, enviaremos um novo link. Confira também a pasta de spam.</span></div>}<div className="form-field"><label htmlFor="email">E-mail</label><input id="email" name="email" type="email" autoComplete="email" placeholder="voce@email.com" required/></div>{showingConfirmation&&<button type="submit" formAction="/api/auth/resend-confirmation" formMethod="post" formNoValidate className="btn secondary resend-confirm-button">Reenviar link de confirmação</button>}<div className="form-field"><label htmlFor="password">Senha</label><input id="password" name="password" type="password" autoComplete="current-password" required/><Link href="/esqueci-senha" style={{fontSize:11,color:"var(--green)"}}>Esqueci minha senha</Link></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn" style={{width:"100%",marginTop:8}}>Entrar</button><p style={{textAlign:"center",fontSize:12}}>Ainda não tem conta? <Link href="/cadastro" style={{color:"var(--green)",fontWeight:700}}>Criar acesso profissional</Link></p><p style={{textAlign:"center",fontSize:12}}>Acessando como cliente? <Link href="/cliente/entrar" style={{color:"var(--green)",fontWeight:700}}>Entre na sua agenda</Link></p></form></main>;
}
